# -*- coding: utf-8 -*-
# -*- mode: org -*-
#+Title:   Numerical/Software Chaos and Reproducibility Issues in HPC
#+Author: Arnaud Legrand\medskip\newline\logoInstitutions
#+DATE:  \vspace{3cm} Theory Days on \textit{Computational tools in physics:}\newline \textit{performances vs. reproducibility}\smallskip\newline Toulouse/Online, March 2024\newline\begin{overlayarea}{1.05\linewidth}{0cm}\vspace{-3.2cm}\hfill{\mylogo}\end{overlayarea}\vspace{-1.0cm}
#+LANGUAGE: en
#+STARTUP: beamer indent inlineimages logdrawer
#+TAGS: noexport(n)

#+PROPERTY: header-args  :session :eval never-export :exports both
#+DRAWERS: latex_headers

:latex_headers:
#+LaTeX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [10pt,presentation,xcolor={usenames,dvipsnames,svgnames,table}]
# # aspectratio=169
#+OPTIONS:   H:2 num:t toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+LATEX_COMPILER: lualatex -shell-escape
#+LATEX_HEADER: \usedescriptionitemofwidthas{bl}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage{figlatex}
#+LATEX_HEADER: \usepackage[french]{babel}
#+LATEX_HEADER: %\usepackage{DejaVuSansMono}
#+LATEX_HEADER: \usepackage{ifthen,amsmath,amstext,gensymb,amssymb}
#+LATEX_HEADER: \usepackage{relsize}
#+LATEX_HEADER: \usepackage{boxedminipage,xspace,multicol}
#+LATEX_HEADER: %%%%%%%%% Begin of Beamer Layout %%%%%%%%%%%%%
#+LATEX_HEADER: \ProcessOptionsBeamer
#+LATEX_HEADER: \usetheme[numbering=fraction,titleformat=smallcaps,progressbar=frametitle]{metropolis}
#+LATEX_HEADER: \usepackage{fontawesome}
#+LATEX_HEADER: \usecolortheme[named=BrickRed]{structure}
#+LATEX_HEADER: %%%%%%%%% End of Beamer Layout %%%%%%%%%%%%%
#+LATEX_HEADER: \usepackage{array}
#+LATEX_HEADER: \newcolumntype{L}[1]{>{\raggedright\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}
#+LATEX_HEADER: \newcolumntype{C}[1]{>{\centering\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}
#+LATEX_HEADER: \newcolumntype{R}[1]{>{\raggedleft\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}

#+LATEX_HEADER: %%%%%%%%% Begin of Minted Configuration %%%%%%%%%%%%%
#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \makeatletter\newcommand{\verbatimfont}[1]{\renewcommand{\verbatim@font}{\ttfamily#1}}\makeatother
#+LATEX_HEADER: \usepackage{fancyvrb}
#+LATEX_HEADER: \verbatimfont{\scriptsize}%
#+LATEX_HEADER: \let\oldendminted=\endminted
#+LATEX_HEADER: \def\endminted{\oldendminted\vspace{-1em}}
#+LATEX_HEADER: \definecolor{minted-background}{rgb}{.94,.94,.94}
#+LATEX_HEADER: \setminted{style=default}
#+LATEX_HEADER: \setminted{bgcolor=minted-background}
#+LATEX_HEADER: \setminted{frame=lines}
#+LATEX_HEADER: \setminted{linenos=true}
#+LATEX_HEADER: \renewcommand{\theFancyVerbLine}{\sffamily{\tiny\arabic{FancyVerbLine}}}

#+LATEX_HEADER: \setminted{fontsize=\scriptsize}
#+LATEX_HEADER: \usepackage{iftex}
#+LATEX_HEADER: \ifpdftex\usepackage{pmboxdraw}\else\usepackage{fontspec}\setmonofont{DejaVu Sans Mono}\fi % to enable characters like ├ and ─ 

#+LATEX_HEADER: %%%%%%%%% End of Minted Configuration %%%%%%%%%%%%%
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{url} \urlstyle{sf}
#+LATEX_HEADER: \let\alert=\structure % to make sure the org * * works of tools
#+LATEX_HEADER: %\let\tmptableofcontents=\tableofcontents
#+LATEX_HEADER: %\def\tableofcontents{}
#+LATEX_HEADER: \let\hrefold=\href
#+LATEX_HEADER: \usepackage{ifluatex}
#+LATEX_HEADER: \ifpdftex
#+LATEX_HEADER:   \usepackage[normalem]{ulem}\usepackage{soul}
#+LATEX_HEADER:   % \usepackage{color}
#+LATEX_HEADER:   \definecolor{lightorange}{rgb}{1,.9,.7}
#+LATEX_HEADER:   \sethlcolor{lightorange}
#+LATEX_HEADER:   \definecolor{lightgreen}{rgb}{.7,.9,.7}
#+LATEX_HEADER:   \makeatother
#+LATEX_HEADER:      \renewcommand{\href}[2]{\hrefold{#1}{\SoulColor{lightorange}\hl{#2}}}
#+LATEX_HEADER:      % \renewcommand{\uline}[1]{\SoulColor{lightorange}\hl{#1}}
#+LATEX_HEADER:      % \renewcommand{\emph}[1]{\SoulColor{lightorange}\hl{#1}}
#+LATEX_HEADER:   \makeatletter
#+LATEX_HEADER:   \newcommand\SoulColor[1]{%
#+LATEX_HEADER:   \sethlcolor{#1}%
#+LATEX_HEADER:   \let\set@color\beamerorig@set@color%
#+LATEX_HEADER:   \let\reset@color\beamerorig@reset@color}
#+LATEX_HEADER: \else
#+LATEX_HEADER:    \usepackage[soul]{lua-ul}
#+LATEX_HEADER:    \usepackage{tcolorbox}
#+LATEX_HEADER:      \renewcommand{\href}[2]{\hrefold{#1}{\begin{tcolorbox}[colback=orange!30!white,size=minimal,hbox,on line]{#2}\end{tcolorbox}}}
#+LATEX_HEADER:      \let\textttold=\texttt
#+LATEX_HEADER:      \renewcommand\texttt[1]{\begin{tcolorbox}[colback=green!30!white,size=minimal,hbox,on line]{\smaller\textttold{#1}}\end{tcolorbox}}
#+LATEX_HEADER: \fi
#+LATEX_HEADER: % 
#+LATEX_HEADER: % \renewcommand\alert[1]{\SoulColor{lightgreen}\hl{#1}}
#+LATEX_HEADER: % \AtBeginSection{\begin{frame}{Outline}\tableofcontents\end{frame}}
#+LATEX_HEADER: \usepackage[export]{adjustbox}
#+LATEX_HEADER: \graphicspath{{fig/}}
#+LATEX_HEADER: \usepackage{tikzsymbols}
#+LATEX_HEADER: \def\smiley{\Smiley[1][green!80!white]}
#+LATEX_HEADER: \def\frowny{\Sadey[1][red!80!white]}
#+LATEX_HEADER: \def\winkey{\Winkey[1][yellow]}
#+LATEX_HEADER: \def\JDEVlogo{\raisebox{-1.3em}{\includegraphics[height=1cm]{./images/Logo_Grid5000.png}}}
#+LATEX_HEADER: \def\mylogo{\includegraphics[height=2.5cm]{./images/in_science_we_trust.jpg}}
#+LATEX_HEADER: \def\logoInstitutions{\includegraphics[height=.7cm]{./images/Logo-UGA2020.pdf}\quad\includegraphics[height=.7cm]{./images/Logo-CNRS.pdf}\quad\includegraphics[height=.7cm]{./images/Logo-Inria.pdf}\includegraphics[height=.7cm]{./images/Logo-Lig2.pdf}\vspace{-.7cm}}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{shapes.geometric}
#+LATEX_HEADER: \newcommand{\warningsign}{\scalebox{.6}{\tikz[baseline=-.75ex] \node[shape=regular polygon, regular polygon sides=3, inner sep=0pt, draw, thick] {\textbf{!}};}}
#+LATEX_HEADER: %\usepackage{pgf}  
#+LATEX_HEADER: %\logo{\pgfputat{\pgfxy(-2,6.5)}{\pgfbox[center,base]{\includegraphics[height=1cm]{./images/jdevLogo.pdf}}}}

#+LaTeX: \newsavebox{\temp}

#+BEGIN_EXPORT latex
  \newcommand{\myfbox}[2][gray!20]{\bgroup\scalebox{.7}{\colorbox{#1}{{\vphantom{pS}#2}}}\egroup} % \fbox
  %\def\myfbox#1{#1} % \fbox
  \def\HPC{\myfbox[gray!40]{HPC}}
  \def\NET{\myfbox[gray!40]{Network}}
  \def\SG{\myfbox[gray!40]{Smart Grids}}
  \def\ECO{\myfbox[gray!40]{Economics}}
  \def\PRIV{\myfbox[gray!40]{Privacy}}
  \def\TRACING{\myfbox[red!20]{Tracing}}
  \def\SIM{\myfbox[green!20]{Simulation}}
  \def\VIZ{\myfbox[red!40]{Visualization}}
  \def\MODELING{\myfbox[green!40]{Stochastic Models}}
  \def\OPT{\myfbox[blue!20]{Optimization}}
  \def\GT{\myfbox[blue!40]{Game Theory}}
#+END_EXPORT

#+BEGIN_EXPORT latex
\def\etal{\textit{et al.}\xspace}
\def\eg{e.g.,\xspace}
#+END_EXPORT

#+BEGIN_EXPORT latex
\def\changefont#1{%
  \setbeamertemplate{itemize/enumerate body begin}{#1}
  \setbeamertemplate{itemize/enumerate subbody begin}{#1}
  #1}
\makeatletter

\def\rv#1{\ensuremath{\textcolor{blue}{#1}}\xspace} % DarkBlue
#+END_EXPORT

#+BEGIN_EXPORT latex
\newcommand{\Norm}{\ensuremath{\mathcal{N}}\xspace}
\newcommand{\Unif}{\ensuremath{\mathcal{U}}\xspace}
\newcommand{\Triang}{\ensuremath{\mathcal{T}}\xspace}
\newcommand{\Exp}{\ensuremath{\mathcal{E}}\xspace}
\newcommand{\Bernouilli}{\ensuremath{\mathcal{B}}\xspace}
\newcommand{\Like}{\ensuremath{\mathcal{L}}\xspace}
\newcommand{\Model}{\ensuremath{\mathcal{M}}\xspace}
\newcommand{\E}{\ensuremath{\mathbb{E}}\xspace}
\def\T{\ensuremath{\theta}\xspace}
\def\Th{\ensuremath{\hat{\theta}}\xspace}
\def\Tt{\ensuremath{\tilde{\theta}}\xspace}
\def\Y{\ensuremath{y}\xspace}
\def\Yh{\ensuremath{\hat{y}}\xspace}
\def\Yt{\ensuremath{\tilde{y}}\xspace}
\let\epsilon=\varepsilon
\let\leq=\leqslant
\let\geq=\geqslant

\def\Scalebox#1{\scalebox{.9}{#1}}
\def\ScaleboxI#1{\Scalebox{\textit{#1}}}

\def\pillar#1#2{~\hbox{\hspace{-1em}\rlap{#1}\hspace{4cm}\includegraphics[height=1cm]{#2}}}
\verbatimfont{\scriptsize}
\let\oldalert=\alert
#+END_EXPORT
:end:

#+latex: \let\oldsection=\section
#+latex: \def\nosection#1{}
#+latex: \let\section=\nosection

* Reproducibility Crisis
** Reproducibility Crisis
#+latex: \begin{overlayarea}{\linewidth}{10cm}
#+latex: \vspace{1mm}\hspace{-2em}\href{http://www.nature.com/news/1-500-scientists-lift-the-lid-on-reproducibility-1.19970}{\textit{Is there a reproducibility crisis?}}\newline A Nature survey, 2016\newline
#+latex: \vspace{-1mm}
#+latex: \hbox{\hspace{-.1\linewidth}\includegraphics[width=1.2\linewidth]{images/reproducibility-network/rrdays1_slides_3.pdf}\hspace{-.1\linewidth}}
#+latex: 
#+latex: \begin{overlayarea}{\linewidth}{0cm}
#+latex:       \vspace*{-10.6cm}\null\hbox{
#+latex:             \hspace{3.9cm}\includegraphics[height=4.1cm]{images/reproducibility-graphic-online2.jpg}%
#+latex:             \includegraphics[height=4.1cm]{images/reproducibility-graphic-online3.jpg}}
#+latex: \end{overlayarea}
#+latex: \end{overlayarea}
** Reproducible Research: an Umbrella Term
\small
Connexions with:\vspace{-1em}
- *Open* Science/Access/Data/Source/Reviews/Laboratory notebooks/...

Many different *terms* and *issues* depending on the *domain* \vspace{-1em}
- Reproduce, Replicate, Repeat, Rerun, Redo, Reuse, Register, \rlap{Report}\pause
#
- Biology, Oncology :: sample provenance, clinical trials
  #+latex: \hbox{\hfill$\leadsto$ standardized protocols\hspace{-1cm}}
- Psychology, Nutrition :: HARKING, p-hacking \hfill$\leadsto$ pre-registration\pause
- Genomics :: software engineering, comput. reproducibility,
  \rlap{provenance}
- Computational fluid dynamics :: numerical chaos, parallel \rlap{architectures}
- /Artificial Intelligence/ :: most of the above $\winkey$ \pause

#+BEGIN_EXPORT latex
\vspace{-.5em}\begin{center}
  \uline{AFAIC, I care about \alert{\bf transparency}}

  \includegraphics[width=.6\linewidth]{images/iceberg_publication-5.png}
\end{center}
#+END_EXPORT

** Scientific Consensus
#+latex: \hbox{\hspace{-.1\linewidth}\includegraphics[width=1.2\linewidth]{images/logo/open-review.png}\hspace{-.1\linewidth}}

*                                                    :B_ignoreheading
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
#+latex: \let\section=\oldsection
* (HP)Computational Reproducibility Issues
# Sous le terme « reproductibilité de la recherche » se cachent plusieurs problèmes assez différents qui appellent des réponses tout aussi différentes. J’essaierai de clarifier les différentes problématiques liées spécifiquement au calcul et comment certains outils peuvent aider, puis comment le processus de relecture des publications a évolué ces dernières années pour inciter à améliorer les pratiques.
** Classical Computational Science Challenges
\small
#+begin_src shell :results output :exports both
my_code --cfg=magical_param:0.94572 '*.dat' --output foo.csv
#+end_src
# \vspace{-2mm}
#+ATTR_BEAMER: :overlay <+->
- Tracking _parameters_ and _data_  ::  
  #+ATTR_BEAMER: :overlay <.->
  - =*.dat=? Ooh, so did you run this in ~data/2091293-AJXQ37~?
  - Wasn't =mymap.dat= updated since then?
  - That was for =foo.csv=. What about =bar.csv=? Is it reproducible?
- Tracking the process :: (on short/long term)
  - <.-> Why did I run this? What did I learn from it? When did I do this?
- Tracking code _version_ ::  
  - <.-> =my_code= is revision =21b95ecfa0911d6ca87668482b11ab9498edd8f3=
- Tracking software _environment_ ::  
  #+ATTR_BEAMER: :overlay <.->
  - =my_code= depends on a dozen of libraries, which
    depend on dozens of libraries
  - =my_code= was compiled with =clang= =1:9.0-49.1= and =-O3
    -funroll-loops -fno-strict-aliasing -finline-functions ...=
- Handle complex sequences and _reuse_ results :: leverage \rlap{cloud/supercomputers}\newline and their ecosystem (workflow, RJMS, data warehouse)
** Software dependencies: horror stories
****                                                     :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
#+latex: \small\only<+->{}
#+ATTR_BEAMER: :overlay <+->
- Software environment evolution
  # \hfill /Default choices silently evolving/\hspace{1cm}
- OS heterogeneity
  # \hfill /Bug fix? Reimplementing FFT and BLAS?/\hspace{1cm}
- Impact of the compiler
  - \scriptsize Not even mentioning the lack of determinism\newline
    stemming from threads, MPI collective communication, \newline and
    non-associative operations
\vspace{-1.5cm}      
****                                                     :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
#+begin_export latex
   \begin{overlayarea}{\linewidth}{2cm}\vspace{2cm}
      \only<3>{\vspace{-3.2cm}\null\hspace*{5.5cm}\null\includegraphics<3>[width=.52\linewidth]{images/pone_0038234_g005.jpg}}%
      \only<4->{\vspace{-3.8cm}\null\hspace*{6.8cm}\null\includegraphics<4-5>[width=.45\linewidth]{images/rescueHPC_gal1.png}%
      \includegraphics<6->[width=.45\linewidth]{images/rescueHPC_gal2.png}}%    
   \end{overlayarea}
#+end_export

****                                                     :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:

#+LaTeX: \vspace{.2cm}
#+LaTeX: \begin{overlayarea}{\linewidth}{5cm}\scriptsize
  #+LaTeX: \only<2>{\vspace{-2cm}

    #+ATTR_LATEX: :height 3.35cm :center nil
    file:images/plot_1.5.3.png
    #+ATTR_LATEX: :height 3.35cm :center nil
    file:images/plot_2.1.1.png
  #+LaTeX: }%
  #+LaTeX: \only<3>{
    The Effects of FreeSurfer Version, Workstation Type, and Macintosh
    Operating System Version on Anatomical Volume and Cortical Thickness
    Measurements (PLOS ONE, 2012)
  
    #+BEGIN_QUOTE
    Significant differences in volume and cortical thickness were
    revealed *across FreeSurfer versions*:
    - volume: \hspace{1.13cm} 8.8 \pm 6.6% (range 1.3-\oldalert{64.0}%)
    - cortical thickness: 2.8 \pm 1.3% (range 1.1-7.7%) 
    About a factor two smaller differences were found *between* the
    *Mac* and *HP workstations* and *between Mac OSX 10.5 and OSX 10.6*.

    In the context of an ongoing study, _users are discouraged to
    update to a new major release_ of either FreeSurfer or operating
    system.

    Formal assessment of the accuracy of FreeSurfer is desirable.
    #+END_QUOTE
  #+LaTeX: }%
  #+LaTeX: \only<4->{
    Assessing Reproducibility: An Astrophysical Example of
    Computational Uncertainty in the HPC Context (ResCuE-HPC, 2018)

      #+LaTeX: \null\hbox{\hspace{-.4cm}\scalebox{.87}{
      #+ATTR_LATEX: :center nil
      | Compiler     | Optim. | Largest Halo |           | Walltime  |
      |              |        | Avg Mass.    | Std. Err  |           |
      |--------------+--------+--------------+-----------+-----------|
      | gcc@6.2.0    | None   |  2.273E 46   | 1.069E 44 | 22h\pause |
      | gcc@6.2.0    | Normal |  2.266E 46   | 1.218E 44 | 10h       |
      | gcc@6.2.0    | High   |  2.275E 46   | 1.199E 44 | \oldalert<5>9h\pause   |
      |--------------+--------+--------------+-----------+-----------|
      | intel@16.0.3 | None   | \oldalert{22.71} E 46  | 1.587E 44 | 39h       |
      | intel@16.0.3 | Normal | \oldalert{43.30} E 46  | 1.248E 44 | 7h        |
      | intel@16.0.3 | High   |  2.268E 46   | 1.414E 44 | 6h        |
      |--------------+--------+--------------+-----------+-----------|
      | cce@8.5.5    | Low    | \oldalert{43.11} E 46  | 1.353E 44 | 16h       |
      | cce@8.5.5    | Normal |  2.271E 46   | 1.261E 44 | 6h        |
      | cce@8.5.5    | High   |  2.272E 46   | 1.341E 44 | 5h        |
      # |--------------+--------+--------------+----------+----------|
      # | pgi@16.9.0   | Normal |     2.272E46 | 1.326E44 | 13h      |
      # | pgi@16.9.0   | High   |     2.271E46 | 1.191E44 | 10h      |
      #+LaTeX: }}
    #+LaTeX: }
#+LaTeX: \end{overlayarea}
** Floating Points Rounding: the other root of all evil ?
#+LaTeX: \def\round{\texttt{round}}
\small
- Every operation includes implicit rounding.
  #+begin_src python :results output :exports both
  print(2.1-2.0 == 0.1)
  #+end_src

  \vspace{.5em}
  
  #+RESULTS:
  : False

  \pause
  # Fortunately: \round(a)+\round(b)=\round(a+b)=\round(a+b)\newline\pause
- *Unfortunately*: \round(\round(a+b)+c) $\ne$ \round(a+\round(b+c))\newline
  Hence, _operation order matters_. *For a reproducible
  computation, operation order should be preserved!!!*   Which order is more relevant is an other debate  $\winkey$ \pause
- Numerical *instability* may be closer than you think [Rump, 1988]
  $$f(x, y) = 333.75y^6 + x^2(11 x^2 y^2 - y^6 − 121 y^4 − 2)2 + 5.5y^8 + \frac{x}{2y}$$

  #+latex: \centerline{Evaluation of $f(77617.0, 33096.0)$\newline\scalebox{.7}{
  |------------------------------------------+----------------------------------|
  | Single precision                         | \alert{1.172603}                 |
  |------------------------------------------+----------------------------------|
  | Double precision                         | \alert{1.172603}9400531          |
  |------------------------------------------+----------------------------------|
  | Extended precision                       | \alert{1.172603}940053178        |
  |------------------------------------------+----------------------------------|
  | MPFI                                     | [\alert{-0.8273960}59946821368141165..., |
  | (multiple precision interval arithmetic) | \alert{-0.8273960}59946821368141165...] |
  |------------------------------------------+----------------------------------|
  #+latex: }}
  #+latex: \begin{flushright}\scriptsize \href{https://www.teratec.fr/actu/calcul/Workshop_HPC_CFD_EDF_DENIS.pdf}{Courtesy of Christophe Denis}\end{flushright}
At scale (complex code + non-determinism), all this can become particularly
harmful and painful.
** Did I mention we have \textbf{parallel} machines nowadays?
#+BEGIN_EXPORT latex
\begin{overlayarea}{\linewidth}{7cm}\vspace{2mm}
  \begin{center}
    \includegraphics<+>[width=.9\linewidth, page=13]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=14]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=15]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=16]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=17]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=18]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=19]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=20]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=21]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=22]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=23]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=24]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=25]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=26]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=27]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=28]{pdf_sources/langlois.pdf}%
    \only<+>{\vspace{-2mm}
      \begin{flushright}
        \includegraphics[height=4cm]{images/langlois_malpasset.png}\vspace{-3cm}
      \end{flushright}\vspace{-5mm}%\bigskip
      \begin{flushleft}
       \small \texttt{round}(\texttt{round}($a+b$)$+c$) $\ne$\newline \texttt{round}($a+\phantom{}$\texttt{round}$(b+c)$).
       
        These numerical issues can become \\ quite harmful in real use
        cases.
        \vspace{.5cm}
        
        \small TABLE 1.1: Reproducibility failure of the Malpasset test case
      \end{flushleft}\small
      \begin{tabular}{c|c|c|c}
        & The sequential run & a 64 procs run & a 128 procs run \\\hline
        depth H & 0.3500122E-01 & 0.2\alert{748817}E-01 & 0.\alert{1327634}E-01 \\\hline
        velocity U & 0.4029747E-02 & 0.4\alert{935279}E-02 & 0.4\alert{512116}E-02 \\\hline
        velocity V & 0.7570773E-02 & 0.\alert{3422730}E-02 & 0.75\alert{45233}E-02
      \end{tabular}}
  \end{center}
  \only<.>{
  {\bf \alert{Numerical reproducibility?}}: Approximations in the model, in
  the algorithm, in its implementation, in its execution. \medskip

  The whole chain needs to be revisited.}
\end{overlayarea}
\begin{flushright}\scriptsize Courtesy of P. Langlois and R. Nheili\end{flushright}
#+END_EXPORT

** Complexity \leadsto reproducibility issues
\small
The slightest difference \textbf{may} have significant consequences\smallskip

#+begin_export latex
\hbox{\hspace{-1.5em}\begin{tabular}{@{}m{.34\linewidth}m{.33\linewidth}m{.34\linewidth}@{}}
    FreeSurfer\newline \hrefold{https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0038234}{\footnotesize (PLOS ONE, 2012)} & Astrophysics \newline\hrefold{https://stodden.net/papers/ResCuE2018-VSMK.pdf}{\footnotesize (ResCuE-HPC, 2018)}
    & Fluid Dynamics\newline(TELEMAC-2D)\\
    \hline
      \hfill\vbox{\includegraphics[width=\linewidth]{images/pone_0038234_g005.jpg}}\hfill
    & \hfill\vbox{\includegraphics[width=.75\linewidth]{images/rescueHPC_gal1.png}}\hfill
    & \hfill\vbox{\includegraphics[width=\linewidth]{images/langlois_malpasset.png}}\hfill\\\pause
      \null\vspace{-2mm}\scriptsize \centering Software environment problem\newline
      \emph{(permeability + versions differ)}
    & \null\vspace{-2mm}\scriptsize \emph{Numerical chaos} problem\newline
      Compiler optimization influence
    & \null\vspace{-2mm}\scriptsize \emph{Numerical chaos} problem\newline
      Unstable and Parallel Dot-Product
    \end{tabular}}
#+end_export
\pause
1. Controling your *environment* (isolation with containers)
2. Controling your *dependencies* (versions, reproducible recipe)

It is not a good sign if your code is sensitive. You'll need:\vspace{-1mm}
1. \hspace{0cm}\rlap{Perfect control}\null\hspace{4cm}          (debug)
2. \hspace{0cm}\rlap{Variation generation}\null\hspace{4cm}     (test)
3. \hspace{0cm}\rlap{Locate unstable routines}\null\hspace{4cm} (sensibility analysis)
** Main issues
1. Tracking the process, parameters, and data and making them available
   - Version control, laboratory/computational notebooks, archives
2. Tracking/controling the software environment
   - Containers, reproducible environments
3. Handling numerical issues
   - Identifying sources of numerical instabilities
   - Dealing with hardware heterogeneity
** Additional HPC constraints
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: .6
:END:
- Software is complex and difficult to maintain
- Users (scientists) want
  - rapid development
  - rapidly evolving environment
  - old/legacy code
  - efficient code
  - process more data in a shorter time (multi-scale, multi-physics)
  - use AI/neural networks $\winkey$
  - and reproducibility!!!
- Hardware keeps evolving and complexify
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: .5
:END:


#+latex: \includegraphics[width=\linewidth]{images/ai-art-is-theft-buy-real-art.jpg}%
***                                                       :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
\bigskip
\hspace{-1em}I know it's High Performance Computing, but maybe we
should slow \rlap{down}

\emph{There is more to life than increasing its speed \hfill -- Gandhi.}
* Handling Software Environment Chaos
** Complex ecosystems

#+begin_src python :results output :exports both
import matplotlib
print(matplotlib.__version__) 
#+end_src

#+RESULTS:
: 3.5.1

\pause
#+name: python3_apt
#+begin_src shell :results output :exports both
apt show python3-matplotlib
#+end_src

#+latex: \begin{minipage}{1.1\linewidth}
#+RESULTS: python3_apt
#+begin_example
Package: python3-matplotlib
Version: 3.5.1-2+b1
Source: matplotlib (3.5.1-2)
Maintainer: Sandro Tosi <morph@debian.org>
Installed-Size: 27.6 MB
Depends: libjs-jquery, libjs-jquery-ui, python-matplotlib-data (>= 3.5.1), 
         python3-dateutil, python3-pil.imagetk, python3-pyparsing (>= 1.5.6), 
         python3-six (>= 1.4), python3-numpy (>= 1:1.20.0), python3-numpy-abi9, 
         python3 (<< 3.11), python3 (>= 3.9~), python3-cycler (>= 0.10.0), 
         python3-fonttools, python3-kiwisolver, python3-packaging, python3-pil, 
         python3:any, libc6 (>= 2.29), libfreetype6 (>= 2.2.1), 
         libgcc-s1 (>= 3.3.1), libqhull-r8.0 (>= 2020.1), libstdc++6 (>= 11)
Recommends: python3-tk
Suggests: dvipng, ffmpeg, fonts-staypuft, ghostscript, gir1.2-gtk-3.0, inkscape, 
          ipython3, librsvg2-common, python-matplotlib-doc, python3-cairocffi, 
          python3-gi, python3-gi-cairo, python3-gobject, python3-pyqt5, 
          python3-scipy, python3-sip, python3-tornado, texlive-extra-utils, 
          texlive-latex-extra
Enhances: ipython3
Homepage: http://matplotlib.org/
Download-Size: 7,333 kB
APT-Manual-Installed: no
APT-Sources: http://ftp.fr.debian.org/debian unstable/main amd64 Packages
Description: Python based plotting system in a style similar to Matlab (Python 3)
 Matplotlib is a pure Python plotting library designed to bring
 publication quality plotting to Python with a syntax familiar to
 Matlab users. All of the plotting commands in the pylab interface can
 be accessed either via a functional interface familiar to Matlab
 users or an object oriented interface familiar to Python users.
 .
 This package contains the Python 3 version of matplotlib.
#+end_example
#+latex: \end{minipage}

#+BEGIN_EXPORT latex
\begin{overlayarea}{\linewidth}{5cm}
  \pause\vspace{-11.5cm}\hbox{\hspace{-1cm}\includegraphics<+>[width=1.25\linewidth]{images/python3-matplotlib.png}}%
\end{overlayarea}
#+END_EXPORT
** Non-standard ecosystems                                :noexport:B_frame:
:PROPERTIES:
:BEAMER_env: frame
:BEAMER_opt: shrink=8
:END:

- No standard :: neither for installation nor for retrieving the information... $\frowny$
  - Linux (=apt=, =rpm=, =yum=), MacOS X (=brew=, =MacPorts=, =Fink=), \dots

#+LaTeX: \vspace{-1.5em}\pause
*** Two Columns                                                 :B_columns:
:PROPERTIES:
:BEAMER_env: columns
:BEAMER_opt: [onlytextwidth]
:END:
**** Python                                                        :BMCOL:
:PROPERTIES:
:BEAMER_col: .45
:BEAMER_opt: t
:END:

#+name: python_version
#+begin_src python :results output :exports both
import sys
print(sys.version)
import matplotlib
print(matplotlib.__version__)
import pandas as pd
print(pd.__version__)
#+end_src

#+LaTeX:\begin{lrbox}{\temp}\begin{minipage}{2\linewidth}
#+RESULTS: python_version
#+begin_example
3.10.6 (main, Aug 10 2022, 11:19:32) 
    [GCC 12.1.0]
3.5.1
1.3.5
#+end_example
#+LaTeX: \end{minipage}\end{lrbox}\vspace{.6em}\scalebox{.8}{\usebox{\temp}} \pause
**** R                                                             :BMCOL:
:PROPERTIES:
:BEAMER_col: .55
:BEAMER_opt: t
:END:
#+begin_src R :results output :session *R* :exports both
library(ggplot2)
sessionInfo()
#+end_src

#+LaTeX:\begin{lrbox}{\temp}\begin{minipage}{2\linewidth}
#+RESULTS:
#+begin_example
R version 4.2.2 Patched (2022-11-10 r83330)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux bookworm/sid

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 ...
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
 [1] stats graphics grDevices utils datasets methods base     
other attached packages:
 [1] ggplot2_3.4.0
loaded via a namespace (and not attached):
 [1] fansi_0.5.0      withr_2.5.0      assertthat_0.2.1 dplyr_1.0.10    
 [5] utf8_1.2.2       grid_4.2.2       R6_2.5.1         DBI_1.1.1       
 [9] lifecycle_1.0.3  gtable_0.3.0     magrittr_2.0.1   scales_1.2.1    
[13] pillar_1.8.1     rlang_1.0.6      cli_3.5.0        generics_0.1.3  
[17] vctrs_0.5.1      glue_1.6.2       munsell_0.5.0    compiler_4.2.2  
[21] pkgconfig_2.0.3  colorspace_2.0-2 tidyselect_1.2.0 tibble_3.1.8
#+end_example
#+LaTeX: \end{minipage}\end{lrbox}\vspace{.6em}\scalebox{.8}{\usebox{\temp}}  
** Potential solutions: Containers and Package Managers
#+ATTR_LATEX: :align @{}C{2.0cm}C{2.3cm}C{7cm}@{}
| The good                                                                                                      | The bad                                                                                                                        | The uggly                                               |
| \includegraphics[height=1cm]{images/logo/Guix_logo.png}\includegraphics[height=1cm]{images/logo/nix_logo.png} | \includegraphics[height=1cm]{images/logo/docker_logo.png}\includegraphics[height=1cm]{images/logo/singularity_logo.png}\qquad  | \includegraphics[height=.7cm]{images/logo/reprozip.png}\includegraphics[height=.7cm]{images/logo/conda.png} |
*** Automatic tracking\pause
*** Containers
- *Pros*: \quad Lightweight, \quad Good isolation, \quad Easy to use
   #+latex: \only<2>{
  - Running as easy as =docker run <img> <cmd>=
  - Building images: =docker build -f <Dockerfile>=
  - Sharing through the [[https://hub.docker.com/][Docker Hub]]: =docker pull/push <img>=
  #+latex: }\pause
- *Cons*: \quad Opaque, \quad Container build is generally not reproducible
  #+latex: \begin{block}{}<3>\vspace{-1.1cm}
  #+latex: \hspace{.8cm}\begin{overlayarea}{.8\linewidth}{4cm}
  - Recipes rarely follow /reproducibility good practices/\vspace{-.2cm}
    #+begin_src shell :results output :exports both
    FROM ubuntu:20.04
    RUN apt-get update
         && apt-get upgrade -y
         && apt-get install -y ...
    #+end_src
    #+latex: \vspace{.2cm}
    + Choose a *stable* image (and the smallest possible)
    + Include only the necessary libraries (e.g. no graphics libs)
    + Avoid system updates (instead freeze sources)
  #+latex: \end{overlayarea}
  #+latex: \end{block}
  \pause
#+latex: \vspace{-4cm}  
*** Package managers \quad (the uggly and the good)
- Language specific:
  #+latex: \hbox{
    =pip/pipenv/virtualenv=, =conda,= =CRAN/Bioconductor=
  #+latex: \hspace{-3cm}}
  - *Limits*:
    #+latex: \hbox{version management, durability, permeable, language centric\hspace{-1cm}}
- *GUIX/NiX* = Full-fledged functional package manager
  - Native support for environment (/à la git/)
  - Isolation through =--pure=
  - Recompile from source (cache recommended)
    
# #+LaTeX: \begin{center}
# #+LaTeX: \includegraphics[height=1cm]{images/logo/Guix_logo.png}
# #+LaTeX: \includegraphics[height=1cm]{images/logo/nix_logo.png}
# #+LaTeX: \includegraphics[height=1cm]{images/logo/docker_logo.png}
# #+LaTeX: \includegraphics[height=1cm]{images/logo/singularity_logo.png}\qquad
# #+LaTeX: \includegraphics[height=.8cm]{images/logo/reprozip.png} \qquad
# #+LaTeX: \end{center}
** Describing Software/Hardware dependencies
- Runtime dependencies :: interpreter, libraries, other programs
- Build dependencies :: compilers, headers, =autotools/cmake=, etc.\bigskip\pause

- Version :: a loose description
  - =v_1.4.2= \pause (commit =78c293967830979f988b39cea2587a7c26b=),
    \pause
    #+latex: \hbox{%
    (built/run in /this/ _environment_ with /such and such/ _options_)
    #+latex: }\pause
  - =v_1.5= or =v_1.4.3= are often /better/ than =v_1.4.2= \pause
  - Convenient but very problematic for reproducibility\pause
- Package set :: order actually matters (side effects)
  - Installing =A=, then =B= may be different from installing =B=, then =A=
** Debian dependencies
#+begin_src shell :results output :exports both
dpkg --status python3-matplotlib
#+end_src

#+begin_export latex
\begin{Verbatim}[fontsize=\scriptsize,commandchars=\\\{\}]
Package: python3-matplotlib
Version: 3.6.3-1+b1
Source: matplotlib (3.6.3-1)
Depends: libjs-jquery, libjs-jquery-ui, python-matplotlib-data (\structure{>= 3.6.3}), 
         python3-dateutil, python3-pil.imagetk, python3-pyparsing (\structure{>= 1.5.6}), 
         python3-six (\structure{>= 1.4}), python3-numpy (\structure{>= 1:1.22.0}), python3-contourpy,
         python3 (\structure{<< 3.12}), python3 (\structure{>= 3.11~}), python3-numpy-abi9, 
         python3-cycler (\structure{>= 0.10.0}), python3-fonttools, python3-kiwisolver, 
         python3-packaging, python3-pil, python3:any, libc6 (\structure{>= 2.34}), 
         libfreetype6 (\structure{>= 2.2.1}), libgcc-s1 (\structure{>= 3.3.1}), 
         libqhull-r8.0 (\structure{>= 2020.1}), libstdc++6 (\structure{>= 11})
\end{Verbatim}
#+end_export
# #+RESULTS:
# #+begin_example
# Package: python3-matplotlib
# Version: 3.6.3-1+b1
# Source: matplotlib (3.6.3-1)
# Depends: libjs-jquery, libjs-jquery-ui, python-matplotlib-data (\structure{>= 3.6.3}), 
#          python3-dateutil, python3-pil.imagetk, python3-pyparsing (\structure{>= 1.5.6}), 
#          python3-six (\structure{>= 1.4}), python3-numpy (\structure{>= 1:1.22.0}), python3-contourpy,
#          python3 (\structure{<< 3.12}), python3 (\structure{>= 3.11~}), python3-numpy-abi9, 
#          python3-cycler (\structure{>= 0.10.0}), python3-fonttools, python3-kiwisolver, 
#          python3-packaging, python3-pil, python3:any, libc6 (\structure{>= 2.34}), 
#          libfreetype6 (\structure{>= 2.2.1}), libgcc-s1 (\structure{>= 3.3.1}), 
#          libqhull-r8.0 (\structure{>= 2020.1}), libstdc++6 (\structure{>= 11})
# #+end_example

\pause On a given day:
- *Several* versions of each package are available on the server
- Installing the *latest version* of a package may require upgrading *some* other packages
** Loose vs. strict dependencies in picture
\centering
#+latex: \includegraphics<+>{images/dep/debian_graph_init.pdf}%
#+latex: \includegraphics<+>[scale=.8]{images/dep/debian_graph_timeline1.pdf}%
#+latex: \includegraphics<+>[scale=.8]{images/dep/debian_graph_timeline2.pdf}%
#+latex: \includegraphics<+>[scale=.8]{images/dep/debian_graph_timeline3.pdf}%
#+latex: \includegraphics<+>[scale=.8]{images/dep/debian_graph_timeline4.pdf}%
#+latex: \includegraphics<+>[scale=.8]{images/dep/debian_graph_timeline5.pdf}%
#+latex: \includegraphics<+>[scale=.8]{images/dep/debian_graph_timeline6.pdf}%
#+latex: \includegraphics<+>[scale=.8]{images/dep/debian_graph_timeline7.pdf}%
** GUIX in a Nutshell (1/2)
\small
GUIX is not a +container technology+, it is meant for *package management*!\pause\vspace{-.5em}
- A GUIX *recipe* (aka =manifest.scm=)\vspace{-.5em}
  #+begin_src emacs-lisp
(specifications->manifest
   (list "hello" "coreutils"))
  #+end_src
  #+begin_src shell :results output :exports both
guix shell -C -m manifest.scm -- ls /   # -C = --container
  #+end_src
  \pause\vspace{.5em}
- The description of the *versions* is in the =manifest.scm=\vspace{-.5em}
  #+begin_src shell :results output :exports both
guix describe -f channels > channels.scm
  #+end_src
  #+begin_src emacs-lisp
(list (channel
      (name 'guix)
      (url "https://git.savannah.gnu.org/git/guix.git")
      (branch "master")
      (commit
        "d09a4cc7c739f4201821623f62c69bcef9c20f52")
      (introduction
        (make-channel-introduction
          "9edb3f66fd807b096b48283debdcddccfea34bad"
          (openpgp-fingerprint
            "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA")))))
  #+end_src
  \pause\vspace{.5em}
- A *time-machine*\vspace{-.5em}
  #+begin_src shell :results output :exports both
guix time-machine -C channels.scm -- shell -m manifest.scm -- ls /
  #+end_src
** GUIX in a Nutshell (2/2)
\small
- Under the hood:
  - A *deamon* compiles everything in a collection of directories =/gnu/store/8fpk2cja3f07xls48jfnpgrzrljpqivr-coreutils-8.32/= 
  - All the directories are assembled (with symlinks) in a =/gnu/store/j5964hh821p2h5mcadpvj16l1m9330gv-profile/= dir
  - Environment variables (=PATH=, =LD_LIBRARY_PATH=, ...) are updated accordingly\pause
- Several *containerization* options\vspace{-.5em}
  #+begin_src emacs-lisp :tangle init.el
  guix shell --container coreutils -- ls
  guix shell coreutils -- ls   # Fully permeable: expends the env, ...
  #+end_src
  \vspace{.5em}\pause
- Various *export* formats (=docker=, =squashfs=, =debian=, =tarball=, =module=, =relocatable=...)\vspace{-.5em}
  #+begin_src shell :results output :exports both
  guix pack --format=docker --save-provenance -m manifest.scm 
  #+end_src
  \vspace{.5em}
  Allows to carefully control/nest environments and adapt to your context
- For more information: [[https://hpc.guix.info/][https://hpc.guix.info/]]
  - Lastest Guix Workshop on HPC was held in Bordeaux on Nov. 7, 2024,
    after the JCAD
  - Check out the [[https://hpc.guix.info/events/2021/caf%C3%A9-guix/][Café Guix]]
* Handling Numerical Chaos
** Is there a baseline to compare with ?
- Baseline :: From previously established results (e.g. a sequential
  test-case with =-O0=), checked for indirect confirmations
  (e.g. physical properties such as energy are conserved)
  - Until an error is found...
- +Bitwise reproducibility+ :: may be out \rlap{of reach}\newline
  CESM $\approx$ two million lines across 13,000 subroutines and 3,000 functions
  
- Community Earth System Model - Ensemble Consistency Test (CESM-ECT) :: 
  A suite of statistical tests to determine whether a new simulation
  set up (new machine, compiler, etc.) is statistically
  distinguishable from an accepted ensemble.
  - Then try to perform root-cause-analysis of numerical discrepency
    by comparing snapshots of specic variables.

Still, bitwise reproducibility makes debugging easier. Is there
anything we can do in this direction ?

** Reproducible BLAS
\small
Optimized BLAS involve FMA, tiling, cache optimization, loop
unrolling, vectorization (SSE, AVX, AVX-512), dynamic resource
allocations\dots

Use accumulators, binning, and distillation: /TwoProd/, /FastAccSum/, /HybridSum/, /iFastSum/...
- ReproBLAS :: https://bebop.cs.berkeley.edu/reproblas/ (2013-2018)
  - Matrix-matrix multiply, matrix-vector multiply, and reductions
    (namely summation, absolute value summation, dot product, and
    2-norm) for the 4 basic types of data: double, float, double
    complex, and float complex.
  - Future versions (under development) will include: trsv, trsm, OpenMP, MPI
- ExBLAS :: Exact (fast, accurate, and reproducible) BLAS (2014-2016)
  - Intel Xeon Phi many-core accelerator, and both NVIDIA and AMD GPUs
  - ExSUM, ExDOT, ExGEMV, ExTRSV, ExGEMM
- RARE-BLAS :: Reproducible, Accurately Rounded and Efficient BLAS (2016-2017)
  - OpenMP and MPI
** Code Bisection at RunTime
*\bf CADNA and VERROU* (2014-...) stochastic rounding through =valgrind=
  (see [[https://www.teratec.fr/actu/calcul/Workshop_HPC_CFD_EDF_DENIS.pdf][talk by C. Denis]])
  # Écoles thématiques PRECIS
  - Each floating point operation is computed three times using a *random rounding* modes.
    The number of exact significant digits is then estimated from these three samples
  - *Delta-Debugging* to locate which parts of the analyzed source code are likely to be responsible numerical instabilities.
  - Provides *location/type* (e.g. =UNSTABLE CANCELLATION=) of the
    detected numerical instability
  - *Common sources of instability*
    - Parallel dot products + =MPI_Reduce=
    - Aggregation of contributions from the ranks
  - After the round-off error *analysis*
    - Replace or modify algorithms leading to poor precision
    - Use compensated algorithms
    - Use multi-precision arithmetic (for example MPFR)
** Code Bisection at Compile Time
*** Quote                                                           :BMCOL:
:PROPERTIES:
:BEAMER_col: .6
:END:
*\bf FLiT* [[https://pruners.github.io/flit/][https://pruners.github.io/flit/]] (compare compilation options)
at file/symbol granularity
  #+begin_quote
  \scriptsize In practice, this modality of search has helped us
  successfully attribute root causes down to a small set of
  functions. For example, in [...], FLiT-based testing revealed that *a
  compiler optimization level that involved the use of =AVX2=, =FMA=, and
  higher precision intermediate floating-point values* produced a
  result that had a relative difference of 193% from the baseline of
  =g++ -O2=. The $L_2$ norm over the mesh went from approximately 5 to
  15 after the optimizations. Using Symbol Bisect, the problem was
  located to be within one simple function that calculates
  $M = M+aAA^T$

  -- /Keeping Science on Keel When Software Moves/, [[https://cacm.acm.org/research/keeping-science-on-keel-when-software-moves/][CACM 2021]]
  #+end_quote
*** Figure                                                          :BMCOL:
:PROPERTIES:
:BEAMER_col: .4
:END:

#+latex: \hbox{\hspace{-.25\linewidth}\rlap{\includegraphics[width=1.3\linewidth]{images/FLiT.pdf}}}
** My intuition / opinion
Using a task based model (/à la/ [[https://starpu.gitlabpages.inria.fr/][StarPU]]) may help
- More *modular* code
- Better *exploitation of (heterogeneous)* computing *resources*
- Easier control of *asynchronism* in algorithms
- Improve the /ability/ to *change precision*, to hook *inspectors* on numerical stability, etc.
* A bit of advertising 
** Global Reproducibility Networks
#+begin_center
\bf https://www.ukrn.org/global-networks/
#+end_center
#+latex: \includegraphics[width=\linewidth]{images/reproducibility-network/reproducibility_networks.png}%
** French Reproducibility Network
#+begin_center
\bf http://www.recherche-reproductible.fr/
#+end_center
#+latex: \includegraphics[width=\linewidth]{images/reproducibility-network/reproducibility_network_fr.png}%
** French Reproducibility Network Days: 1st Edition
***                                                                 :BMCOL:
:PROPERTIES:
:BEAMER_col: .53
:END:
*\bf March 2023, Institut Pasteur, Paris*

#+latex: \includegraphics[width=.5\linewidth]{images/reproducibility-network/rrdays1_logo_madics.png}%
#+latex: \includegraphics[width=.5\linewidth]{images/reproducibility-network/rrdays1_logo_pasteur.png}%

\bigskip

/Toward an *inter-disciplinary* look on our respective approaches and definitions/
- /Observational, experimental, statistical, computational, etc./

\medskip

*Identify volunteers*, possible *collaboration* topics, *diversity* of
concerns/practices, *educational resources*,...
*** affiche                                                         :BMCOL:
:PROPERTIES:
:BEAMER_col: .5
:END:
#+latex: \includegraphics[width=\linewidth]{images/reproducibility-network/rrdays1_affiche.pdf}%

** French Reproducibility Network Days: 2nd Edition
#+begin_center
  #+latex: \includegraphics[width=.9\linewidth]{images/reproducibility-network/rrdays2_affiche.png}
  #+latex: % \includegraphics[width=.6\linewidth]{images/reproducibility-network/rrdays2_logos.png}%

  \Large \bf _3rd Edition: March 3-4, 2025 @ Lyon_
#+end_center

** MOOCs on Reproducible Research:
#+latex: \begin{columns}\begin{column}[t]{.76\linewidth}
\alert{MOOC} [[https://learninglab.inria.fr/en/mooc-recherche-reproductible-principes-methodologiques-pour-une-science-transparente/][Reproducible Research: Methodological]] [[https://learninglab.inria.fr/en/mooc-recherche-reproductible-principes-methodologiques-pour-une-science-transparente/][principles for a transparent science]], Inria Learning Lab 
 - Konrad Hinsen, Christophe Pouzat
 - *3rd Edition*: March 2020 -- _..._ (16,800+)
 - Notebooks, version control, simple data formats
#+latex: \end{column}\begin{column}[t]{.15\linewidth}
  #+LaTeX: \begin{overlayarea}{\linewidth}{1cm}\null\hspace{-1.7cm}\includegraphics[width=2\linewidth,valign=t]{images/mooc_rr.png}\end{overlayarea}
#+latex: \end{column}\end{columns}\vspace{-.5em}\pause
\bigskip

*MOOC* [[https://www.fun-mooc.fr/en/courses/reproducible-research-ii-practices-and-tools-for-managing-comput/][Reproducible Research II: Practices and tools for managing]]
[[https://www.fun-mooc.fr/en/courses/reproducible-research-ii-practices-and-tools-for-managing-comput/][computations and data]]  (May-Sep 2024, $\approx$ 2,000)
- Managing data (=FITS/HDF5=, =git annex=)
- Software environment control (=docker=, =singularity=, =guix=)
- Scientific workflow (=make=, =snakemake=)
- +Statistics+, +Numerical Chaos+

* Emacs Setup                                                      :noexport:
This document has local variables in its postembule, which should
allow Org-mode (9) to work seamlessly without any setup. If you're
uncomfortable using such variables, you can safely ignore them at
startup. Exporting may require that you copy them in your .emacs.

#+begin_src emacs-lisp 
(setq org-latex-tables-centered nil)
(setq org-latex-listings 'minted)
(setq org-latex-pdf-process '("lualatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
#+end_src

#+RESULTS:
| lualatex -shell-escape -interaction nonstopmode -output-directory %o %f |

# Local Variables:
# eval: (setq org-latex-tables-centered nil)
# eval: (setq org-latex-listings 'minted)
# eval: (setq org-latex-pdf-process '("lualatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
# End:
