# -*- coding: utf-8 -*-
# -*- mode: org -*-
#+Title:   Toward Reproducible Research in Computer Science
#+Author: Arnaud Legrand\newline Univ. Grenoble Alpes, CNRS, Inria, Grenoble INP
#+DATE: University of Neuchâtel, November 2019\newline *Experimental reproducibility for computer scientists*\hfill \mylogo
#+LANGUAGE: en
#+STARTUP: beamer indent inlineimages logdrawer
#+TAGS: noexport(n)

#+PROPERTY: header-args  :session :eval never-export :exports both
#+DRAWERS: latex_headers

:latex_headers:
#+LaTeX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [10pt,presentation,xcolor={usenames,dvipsnames,svgnames,table}]
#+OPTIONS:   H:2 num:t toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+LATEX_COMPILER: lualatex
#+LATEX_HEADER: \usedescriptionitemofwidthas{bl}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage{figlatex}
#+LATEX_HEADER: \usepackage[french]{babel}
#+LATEX_HEADER: %\usepackage{DejaVuSansMono}
#+LATEX_HEADER: \usepackage{ifthen,amsmath,amstext,gensymb,amssymb}
#+LATEX_HEADER: \usepackage{boxedminipage,xspace,multicol}
#+LATEX_HEADER: %%%%%%%%% Begin of Beamer Layout %%%%%%%%%%%%%
#+LATEX_HEADER: \ProcessOptionsBeamer
#+LATEX_HEADER: \usetheme[numbering=fraction,titleformat=smallcaps,progressbar=frametitle]{metropolis}
#+LATEX_HEADER: \usepackage{fontawesome}
#+LATEX_HEADER: \usecolortheme[named=BrickRed]{structure}
#+LATEX_HEADER: %%%%%%%%% End of Beamer Layout %%%%%%%%%%%%%
#+LATEX_HEADER: \usepackage{verbments}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{url} \urlstyle{sf}
#+LATEX_HEADER: \let\alert=\structure % to make sure the org * * works of tools
#+LATEX_HEADER: %\let\tmptableofcontents=\tableofcontents
#+LATEX_HEADER: %\def\tableofcontents{}
#+LATEX_HEADER:  \usepackage[normalem]{ulem}
#+LATEX_HEADER:  \usepackage{color,soul}
#+LATEX_HEADER:  \definecolor{lightorange}{rgb}{1,.9,.7}
#+LATEX_HEADER:  \sethlcolor{lightorange}
#+LATEX_HEADER:  \definecolor{lightgreen}{rgb}{.7,.9,.7}
#+LATEX_HEADER:  \let\hrefold=\href
#+LATEX_HEADER:  \renewcommand{\href}[2]{\hrefold{#1}{\SoulColor{lightorange}\hl{#2}}}
#+LATEX_HEADER: % \renewcommand{\uline}[1]{\SoulColor{lightorange}\hl{#1}}
#+LATEX_HEADER: % \renewcommand{\emph}[1]{\SoulColor{lightorange}\hl{#1}}
#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER: \newcommand\SoulColor[1]{%
#+LATEX_HEADER:   \sethlcolor{#1}%
#+LATEX_HEADER:   \let\set@color\beamerorig@set@color%
#+LATEX_HEADER:   \let\reset@color\beamerorig@reset@color}
#+LATEX_HEADER: \makeatother
#+LATEX_HEADER: \let\oldtexttt=\texttt
#+LATEX_HEADER: % \renewcommand\texttt[1]{\SoulColor{lightgreen}\hl{\tt#1}}
#+LATEX_HEADER: % \renewcommand\alert[1]{\SoulColor{lightgreen}\hl{#1}}
#+LATEX_HEADER: % \AtBeginSection{\begin{frame}{Outline}\tableofcontents\end{frame}}
#+LATEX_HEADER: \graphicspath{{fig/}}
#+LATEX_HEADER: \usepackage{tikzsymbols}
#+LATEX_HEADER: \def\smiley{\Smiley[1][green!80!white]}
#+LATEX_HEADER: \def\frowny{\Sadey[1][red!80!white]}
#+LATEX_HEADER: \def\winkey{\Winkey[1][yellow]}
#+LATEX_HEADER: \def\mylogo{\includegraphics[height=2.5cm]{./images/in_science_we_trust.jpg}}

#+BEGIN_EXPORT latex
  \newcommand{\myfbox}[2][gray!20]{\bgroup\scalebox{.7}{\colorbox{#1}{{\vphantom{pS}#2}}}\egroup} % \fbox
  %\def\myfbox#1{#1} % \fbox
  \def\HPC{\myfbox[gray!40]{HPC}}
  \def\NET{\myfbox[gray!40]{Network}}
  \def\SG{\myfbox[gray!40]{Smart Grids}}
  \def\ECO{\myfbox[gray!40]{Economics}}
  \def\PRIV{\myfbox[gray!40]{Privacy}}
  \def\TRACING{\myfbox[red!20]{Tracing}}
  \def\SIM{\myfbox[green!20]{Simulation}}
  \def\VIZ{\myfbox[red!40]{Visualization}}
  \def\MODELING{\myfbox[green!40]{Stochastic Models}}
  \def\OPT{\myfbox[blue!20]{Optimization}}
  \def\GT{\myfbox[blue!40]{Game Theory}}
#+END_EXPORT

#+BEGIN_EXPORT latex
\def\etal{\textit{et al.}\xspace}
\def\eg{e.g.,\xspace}
#+END_EXPORT

#+BEGIN_EXPORT latex
\def\changefont#1{%
  \setbeamertemplate{itemize/enumerate body begin}{#1}
  \setbeamertemplate{itemize/enumerate subbody begin}{#1}
  #1}
\makeatletter
\newcommand{\verbatimfont}[1]{\renewcommand{\verbatim@font}{\ttfamily#1}}
\makeatother
\verbatimfont{\scriptsize}%small
\let\endmintedbak=\endminted
\def\endminted{\endmintedbak\vspace{-1cm}}
#+END_EXPORT

#+BEGIN_EXPORT latex
\newcommand{\Norm}{\ensuremath{\mathcal{N}}\xspace}
\newcommand{\Unif}{\ensuremath{\mathcal{U}}\xspace}
\newcommand{\Triang}{\ensuremath{\mathcal{T}}\xspace}
\newcommand{\Exp}{\ensuremath{\mathcal{E}}\xspace}
\newcommand{\Bernouilli}{\ensuremath{\mathcal{B}}\xspace}
\newcommand{\Like}{\ensuremath{\mathcal{L}}\xspace}
\newcommand{\Model}{\ensuremath{\mathcal{M}}\xspace}
\newcommand{\E}{\ensuremath{\mathbb{E}}\xspace}
\def\T{\ensuremath{\theta}\xspace}
\def\Th{\ensuremath{\hat{\theta}}\xspace}
\def\Tt{\ensuremath{\tilde{\theta}}\xspace}
\def\Y{\ensuremath{y}\xspace}
\def\Yh{\ensuremath{\hat{y}}\xspace}
\def\Yt{\ensuremath{\tilde{y}}\xspace}
\let\epsilon=\varepsilon
\let\leq=\leqslant
\let\geq=\geqslant
#+END_EXPORT
:end:

** Common beliefs                                                 :noexport:
\it
- RR mainly allows to fight scientific misconduct (e.g.,
  fraud). That's nice but I'm honnest so just let me do my work!
  \medskip\pause
- RR is all about re-executing the same code, even if the code is
  stupid and makes wrong computation. It's pointless! \medskip\pause
- My student has done everything with org-jupyter-studio-mode.
  Now he's gone and I can't reuse what he did. See, what's the point?
  RR does not help! \medskip\pause
- RR is about controling and checking everything, which slows down the
  scientific discovery process. Changing the way we work and publish
  may be harmful!
* Reproducibility crisis ?
** Public Evidence for a Lack of Reproducibility
\small
#+LaTeX: \vspace{-.3cm}\hspace{-.1\linewidth}\begin{overlayarea}{1.1\linewidth}{8cm}
#+LaTeX:   \begin{overlayarea}{\linewidth}{0cm}
#+LaTeX:    \vspace{1.4cm}~\hspace{.05\linewidth}\includegraphics[width=\linewidth]{images/reproducibility_crisis_headlines.pdf}
#+LaTeX:    \end{overlayarea}
- J.P. Ioannidis. /[[http://www.plosmedicine.org/article/info:doi/10.1371/journal.pmed.0020124][Why Most Published Research Findings Are False]]/
  PLoS Med. 2005.
- /[[http://mescal.imag.fr/membres/arnaud.legrand/teaching/2011/EP_lies.pdf][Lies, Damned Lies, and Medical Science]]/, The Atlantic. Nov, 2010
- /[[http://www.nature.com/news/reproducibility-a-tragedy-of-errors-1.19264][Reproducibility: A tragedy of errors]]/, Nature, Feb 2016.
- Steen RG, /[[http://dx.doi.org/10.1136/jme.2010.040923][Retractions in the scientific literature: is the incidence]]/
  \newline /[[http://dx.doi.org/10.1136/jme.2010.040923][of research fraud increasing?]]/. J. Med. Ethics 37, 2011
#+LaTeX: \end{overlayarea}
#+LaTeX: \vspace{-.5cm}~\begin{flushright}\scriptsize \bf Courtesy V. Stodden, SC, 2015\hspace{.35\linewidth}\null\end{flushright}

** Scientific Misconduct ? What are the Consequences ?
# #+LaTeX: \begin{overlayarea}{\linewidth}{7.6cm}\null\vspace{-.4cm}

\small *[[http://www.nytimes.com/2011/07/08/health/research/08genes.html][The Duke University scandal with scientific misconduct on lung
cancer]]*

\vspace{-.2cm}\small
# 1294 - 1300
- /Nature Medicine/ - 12,  (2006) *Genomic signatures to
  guide the use of chemotherapeutics*, by
  #+LaTeX: \bgroup\scriptsize
  Anil Potti and 16 other researchers from Duke and USF
  #+LaTeX: \egroup
- Major commercial labs licensed it and were about to start using it
  before two statisticians discovered and publicized its faults\vspace{-.2cm}
  #+BEGIN_EXPORT latex
  \begin{block}{}\scriptsize
  Dr. Baggerly and Dr. Coombes found errors almost immediately. Some seemed careless — moving a row or a column over by one in a giant spreadsheet — while others seemed inexplicable. The Duke team shrugged them off as “clerical errors.”
  \end{block}\vspace{-1em}
  \begin{block}{}\scriptsize
  The Duke researchers continued to publish papers on their genomic signatures in prestigious journals. Meanwhile, they started three trials using the work to decide which drugs to give patients.
  \end{block}
  #+END_EXPORT
- [[http://en.wikipedia.org/wiki/Anil_Potti][Ten papers coauthored in
  prestigious journals were retracted in Jan 2011]]\pause
More ? In 2015, [[https://en.wikipedia.org/wiki/Dong-Pyou_Han][Dong-Pyou Han]] was sentenced to *57 months imprisonment* and
*fined US $7.2 million* for fabricating data in HIV vaccine trials!

\bgroup\bf *Bad science is deleterious*\egroup
- It is used to backup stupid politics, it affects people's life, ...
- It blurs the frontier between scientists and crooks
** Unfortunate mistakes
#+BEGIN_EXPORT latex
  \vspace{.5cm}
  \begin{columns}
    \begin{column}{.37\linewidth}
       \includegraphics[width=\linewidth]{images/Chang_proteins.png}
    \end{column}\hfill
    \begin{column}{.6\linewidth}
#+END_EXPORT
*Geoffrey Chang* (Scripps, UCSD) works on crystalography and studies the
structure of cell membrane proteins. 

He specialized in structures of *multidrug resistant transporter
proteins in bacteria*: MsbA de Escheria Choli (Science, 2001), Vibrio
cholera (Mol. Biology, 2003), Salmonella typhimurium (Science, 2005)
\bigskip
#+BEGIN_EXPORT latex
    \end{column}
  \end{columns}
#+END_EXPORT

*2006*: Inconsistencies reveal [[https://people.ligo-wa.caltech.edu/~michael.landry/calibration/S5/getsignright.pdf][a programming mistake]] \newline\vspace{-1em}
   #+BEGIN_QUOTE
   a homemade data-analysis program had flipped two columns of data,
   inverting the electron-density map from which his team had derived
   the protein structure.
   #+END_QUOTE
\medskip

\textbf{5 retractations} that motivate improved software engineering
practices in computational biology
** The "Reproducibility Crisis"                                   :noexport:

#+LaTeX: \begin{columns}\begin{column}[b]{.47\linewidth}
\small "clinical trials in oncology have the highest failure rate
[only 5% are licensed] compared with other therapeutic areas [..]
difficulty to repeat experiments even in the laboratory of the
original investigator"\medskip

\footnotesize *Begley and Ellis*, Nature, 2012. [[https://www.nature.com/articles/483531a][\it Raise standards for
preclinical cancer research]]

#+LaTeX: \end{column}\hfill\begin{column}[b]{.47\linewidth}

file:images/repeatability_arizona.pdf


#+LaTeX: \small 8 ACM conferences and 5 journals $\text{EM}^{\text{no}}$= \alert{the code cannot be provided}\smallskip

\footnotesize Collberg, Christian \etal, [[http://reproducibility.cs.arizona.edu/][\it Measuring Reproducibility in Computer
Systems Research]], 2015

#+LaTeX: \end{column}\end{columns}\bigskip

The scientific process demands the highest standards of \textbf{quality},
\textbf{ethics} and \textbf{rigor}.

** Why are scientific studies so difficult to reproduce?
#+BEGIN_EXPORT latex
\vspace{-.6cm}
\null\hspace{-.2cm}\hbox{
\begin{columns}
  \begin{column}{.38\linewidth}
    \begin{overlayarea}{\linewidth}{8cm}
      \includegraphics[scale=.21]{images/reproducibility-graphic-online2.jpg}\\
      \includegraphics[scale=.21]{images/reproducibility-graphic-online3.jpg}
      % \includegraphics<3>[scale=.25]{images/reproducibility-graphic-online4.jpg}%
      % \includegraphics<4>[scale=.25]{images/reproducibility-graphic-online5.jpg}
    \end{overlayarea}
  \end{column}\hspace{-.1cm}%
  \begin{column}{.68\linewidth}\begin{overlayarea}{\linewidth}{8cm}\vspace{-.7em}
#+END_EXPORT
[[http://www.nature.com/news/1-500-scientists-lift-the-lid-on-reproducibility-1.19970][1,500 scientists lift the lid on reproducibility]], Nature, May 2016

\normalsize _*Social causes*_ \small
- Fraud, conflict of interest (pharmaceutic, \dots)
- *No incentive* to reproduce/check our own work (afap), nor the
  work of others (big results!), nor to allow others to check
  (competition)
- Peer review does not scale: 1+ million articles per year!
_*Methodological or technical causes*_ \small
- The many biases, (apophenia, confirmation, ...), HARKing: *bad designs*
- Selective reporting, weak analysis (*statistics*, *data processing,
  computational errors*)
- *Lack of information, code/raw data unavailable*  

#+BEGIN_EXPORT latex
    \end{overlayarea}
  \end{column}
\end{columns}}
#+END_EXPORT
** Different Reproducibility Concerns
# _Distinguish between:_
# #+LaTeX: \begin{columns}\begin{column}[b]{.4\linewidth}
# - experimental science
# - observational science
# #+LaTeX: \end{column}\begin{column}[b]{.6\linewidth}
# - computational science (simulation)
# - (big) data analysis
# #+LaTeX: \end{column}\end{columns}%\bigskip

- Social Sciences, Oncology, ... :: methodology, statistics
- Genomics :: software engineering, computational reproducibility,
  provenance, ...
- Computational fluid dynamics :: numerical issues\medskip

#+BEGIN_EXPORT latex
\begin{center}
  \includegraphics<+>[width=.9\linewidth]{images/iceberg_publication-1.png}%
  \includegraphics<+>[width=.9\linewidth]{images/iceberg_publication-2.png}%
  \includegraphics<+>[width=.9\linewidth]{images/iceberg_publication-3.png}%
  \includegraphics<+>[width=.9\linewidth]{images/iceberg_publication-4.png}%
  \includegraphics<+->[width=.9\linewidth]{images/iceberg_publication-5.png}\medskip
  
  \uncover<+>{\bf Reproducible Research = Bridging the Gap by working Transparently}
\end{center}
#+END_EXPORT
* Reproducible Research Practices
** "Reproducible Research": First Appearance
*Claerbout & Karrenbach*, 
\scalebox{.75}{meeting of the Society of Exploration Geophysics}, 1992

file:images/clearbout.pdf
** Existing Tools, Emerging Standards
\vspace{1em}
#+LaTeX: \begin{columns}\begin{column}[t]{.4\linewidth}\centering
\bf *Notebooks and workflows*

file:images/jupyterpreview.png

#+LaTeX: \includegraphics[height=.8cm]{images/logo/Jupyter_logo.png}
#+LaTeX: \includegraphics[height=.8cm]{images/logo/OrgMode_logo.png}
#+LaTeX: \includegraphics[height=.8cm]{images/logo/RStudio_logo.png}
file:images/logo/workflows.png

#+LaTeX: \end{column}\begin{column}[t]{.35\linewidth}\centering
\bf *Software environments*

file:images/python3-matplotlib.pdf 
#+ATTR_LaTeX: :width .6\linewidth
file:images/platform_diversity.png

#+LaTeX: \includegraphics[height=1cm]{images/logo/docker_logo.png}
#+LaTeX: \includegraphics[height=1cm]{images/logo/singularity_logo.png}
#+LaTeX: \includegraphics[height=.8cm]{images/logo/reprozip.png}
#+LaTeX: \includegraphics[height=1cm]{images/logo/Guix_logo.png}
#+LaTeX: \includegraphics[height=1cm]{images/logo/nix_logo.png}

#+LaTeX: \end{column}\begin{column}[t]{.35\linewidth}\centering
\bf *Sharing platforms*\bigskip

#+LaTeX: \includegraphics[height=1cm]{images/logo/git_logo.png}
#+LaTeX: \includegraphics[height=1cm]{images/logo/github_logo.png}
#+LaTeX: \includegraphics[height=1cm]{images/logo/gitlab_logo.png}
#+LaTeX: \includegraphics[height=1cm]{images/logo/JupyterHub_logo.png}
#+LaTeX: \includegraphics[height=1cm]{images/logo/ArXiv-web.png}
#+LaTeX: \includegraphics[height=1cm]{images/logo/LogoHAL.png}
#+LaTeX: \includegraphics[height=1cm]{images/logo/Figshare-logo.png}
#+LaTeX: \includegraphics[height=1cm]{images/logo/Zenodo-logo.jpg}
#+LaTeX: \includegraphics[height=1cm]{images/logo/swh-logo.png}

#+LaTeX: \end{column}\end{columns}\bigskip



# - Provenance, mise à disposition, software environment capture,
#   literate programming, etc. Still no perfect solution but much better
#   tools.
#   - notebooks: jupyter/...
#   - containers/... 
#   - github/gitlab/zenodo/swh... to
#   - execution in the cloud: continuous integration and codeocean

** Tool 1: Computational Notebooks/Litterate Programming
#+LaTeX: \includegraphics<+>[width=\linewidth]{images/example_pi_full-1.pdf}%
#+LaTeX: \includegraphics<+>[width=\linewidth]{images/example_pi_full-2.pdf}%
#+LaTeX: \includegraphics<+>[width=\linewidth]{images/example_pi_full-3.pdf}%
#+LaTeX: \includegraphics<+>[width=\linewidth]{images/example_pi_full-4.pdf}%
#+LaTeX: \includegraphics<+>[width=\linewidth]{images/example_pi_full-5.pdf}%
#+LaTeX: \includegraphics<+->[width=\linewidth]{images/example_pi_full-6.pdf}%

#+BEGIN_EXPORT latex
\begin{overlayarea}{\linewidth}{0cm}
  \vspace{-1.2cm}
  \begin{center}
    \includegraphics<+>[height=.8cm]{images/logo/Jupyter_logo.png}
    \includegraphics<.>[height=.8cm]{images/logo/OrgMode_logo.png}
    \includegraphics<.>[height=.8cm]{images/logo/RStudio_logo.png}
  \end{center}
\end{overlayarea}
#+END_EXPORT

*** Export svg pdf                                               :noexport:
#+begin_src shell :results output :exports both
for i in images/example_pi_*.svg ; do
   inkscape $i --export-pdf=`dirname $i`/`basename $i .svg`.pdf;
done
#+end_src

#+RESULTS:
** Tool 2: Fighting Software Environments Nightmare
What is hiding behind a simple
#+begin_src python :results output :exports both
import matplotlib
#+end_src

#+LaTeX: \scriptsize
#+BEGIN_EXAMPLE
Package: python3-matplotlib
Version: 2.1.1-2
Depends: python3-dateutil, python-matplotlib-data (>= 2.1.1-2),
python3-pyparsing (>= 1.5.6), python3-six (>= 1.10), python3-tz,
libjs-jquery, libjs-jquery-ui, python3-numpy (>= 1:1.13.1),
python3-numpy-abi9, python3 (<< 3.7), python3 (>= 3.6~),
python3-cycler (>= 0.10.0), python3:any (>= 3.3.2-2~), libc6 (>=
2.14), libfreetype6 (>= 2.2.1), libgcc1 (>= 1:3.0), libpng16-16 (>=
1.6.2-1), libstdc++6 (>= 5.2), zlib1g (>= 1:1.1.4)
#+END_EXAMPLE
#+BEGIN_EXPORT latex
\begin{overlayarea}{\linewidth}{5cm}
  \pause\vspace{-3cm}\includegraphics<+>[width=\linewidth]{images/python3-matplotlib.png}%
\end{overlayarea}
#+END_EXPORT

** Tool 2: Fighting Software Environments Nightmare
Python and its rapidly evolving environment
#+LaTeX: \null\vspace{-.8em}

#+begin_src shell :results output :exports both
python2 -c "print(10/3)"
python3 -c "print(10/3)"
#+end_src

#+LaTeX: \null\vspace{-1.2em}{\scriptsize
#+RESULTS:
: 3
: 3.3333333333333335
#+LaTeX: }
\pause
#+LaTeX: \null\vspace{-1.5cm}
#+ATTR_LATEX: :height 3cm :center nil
file:images/plot_1.5.3.png
#+ATTR_LATEX: :height 3cm :center nil
file:images/plot_2.1.1.png

\pause 
Cortical Thickness Measurements (PLOS ONE, June 2012):
/FreeSurfer/: /differences were found between the Mac and HP workstations
and between Mac OSX 10.5 and OSX 10.6./ \pause

#+LaTeX: \begin{center}
#+LaTeX: \includegraphics[height=.8cm]{images/logo/reprozip.png} \qquad
#+LaTeX: \includegraphics[height=1cm]{images/logo/docker_logo.png}\qquad
#+LaTeX: \includegraphics[height=1cm]{images/logo/Guix_logo.png}
#+LaTeX: \includegraphics[height=1cm]{images/logo/nix_logo.png}
#+LaTeX: \end{center}

** Tool 3: Fighting Information Loss with Archives
\small
D. Spinellis. /[[https://www.spinellis.gr/sw/url-decay/][The Decay and Failures of URL
References]]/. CACM, 46(1), Jan 2003.\smallskip

#+BEGIN_QUOTE
  The half-life of a referenced URL is approximately 4 years from its
  publication date.
#+END_QUOTE
P. Habibzadeh. /[[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3885908/][Decay of References to Web sites in Articles Published
in General Medical Journals: Mainstream vs Small Journals]]/. Applied
Clinical Informatics. 4 (4), 2013
#+BEGIN_QUOTE
   half life ranged from 2.2 years in EMHJ to 5.3 years in BMJ
#+END_QUOTE
\normalsize\pause
- Article archives :: 
  #+LaTeX: \raisebox{-1.5ex}{\includegraphics[height=.8cm]{images/logo/ArXiv-web.png}}
  #+LaTeX: \raisebox{-1.5ex}{\includegraphics[height=.8cm]{images/logo/LogoHAL.png}}

- Data archives ::
  #+LaTeX: \raisebox{-1.5ex}{\includegraphics[height=.8cm]{images/logo/Figshare-logo.png}}
  #+LaTeX: \raisebox{-1.5ex}{\includegraphics[height=.8cm]{images/logo/Zenodo-logo.jpg}}

- Software Archive ::
  #+LaTeX: \raisebox{-2.4ex}{\includegraphics[height=1cm]{images/logo/swh-logo.png}}

#+LaTeX: \raisebox{-1ex}{\includegraphics[height=.8cm]{images/logo/git_logo.png}}
#+LaTeX: \raisebox{-.5ex}{\includegraphics[height=.8cm]{images/logo/github_logo.png}} or
#+LaTeX: \raisebox{-1.4ex}{\includegraphics[height=.8cm]{images/logo/gitlab_logo.png}}
$=$ awesome collaborations $\ne$ archive

** Changing Research Practices
#+LaTeX: \hbox{\bf\normalsize \uline{Soft. Engineering}, \uline{Statistics}, and Reproducible Research in the \alert{curricula}}

#+LaTeX: \begin{columns}\begin{column}{.5\linewidth}
file:images/mooc_rr.png
#+LaTeX: \end{column}\hspace{-.1\linewidth}\begin{column}{.6\linewidth}\vspace{-.8em}
# - [[https://rr-france.github.io/bookrr/][Webinars on RR]] 2016-2017
- [[https://rr-france.github.io/bookrr/][Book on RR]]
  \bgroup\footnotesize /Vers une recherche reproductible: Faire évoluer ses pratiques/\egroup
- [[https://learninglab.inria.fr/en/mooc-recherche-reproductible-principes-methodologiques-pour-une-science-transparente/][\bf MOOC on RR]] \bgroup\small(3rd edition Feb. 2020)\egroup
- A *new "Advanced RR" MOOC* \scalebox{.8}{(Oct. 2020)}\footnotesize
  - \footnotesize Software environment control (Docker)
  - \footnotesize Scientific workflow (snakemake)
  - \footnotesize Managing data (HDF5, archiving)
#+LaTeX: \end{column}\end{columns}
*Manifesto*: "\textit{I solemnly pledge}" ([[https://hal.inria.fr/hal-01367344/document][WSSSPE]], [[http://lorenabarba.com/gallery/reproducibility-pi-manifesto/][Lorena Barba]], [[https://www.go-fair.org/fair-principles/][FAIR]])\footnotesize\vspace{-.4em}
  1. I will teach my graduate students about _reproducibility_
  2. All our research code (and writing) is under _version control_
  3. We will always carry out _verification_ and _validation_
  4. We will _share_ data, plotting script & figure _under CC-BY_
  5. We will upload the _preprint_ to arXiv at the time of submission of a paper
  6. We will _release code_ at the time of submission of a paper
  7. We will add a _"Reproducibility" declaration_ at the end of each paper
  8. I will keep an _up-to-date web presence_

** Changing Publishing Practices
- Artifact evaluation and ACM badges ::  
     #+BEGIN_CENTER
     \includegraphics[height=1cm]{images/ae_badge1.png}
     \includegraphics[height=1cm]{images/ae_badge2.png}
     \includegraphics[height=1cm]{images/acm_badges.pdf}     
     #+END_CENTER
- Major conferences ::  
  - [[https://sc19.supercomputing.org/submit/reproducibility-initiative/][Supercomputing]]: Artifact Description (AD) *mandatory*, Artifact
    Evaluation (AE) still *optional*, *Double blind* vs. *RR*
  - [[https://nips.cc/Conferences/2019/CallForPapers][NeurIPS]], [[https://reproducibility-challenge.github.io/iclr_2019/][ICLR]]: *open reviews*, reproducibility challenge

    [[https://www.youtube.com/watch?v=Kee4ch3miVA][Joelle Pineau @ NeurIPS'18]]
    #+LaTeX: \includegraphics[width=.4\linewidth]{images/joelle_pineau.jpg}
  - [[http://db-reproducibility.seas.harvard.edu/papers/index.html][ACM SIGMOD 2015-2019]], Most Reproducible Paper Award... \medskip
- Mentalitie are evolving :: people care, make stuff available, errors
     are found and fixed

* What about Computer Science ?
** All this is about Computational Sciences. Should we care ?
_Computer Science_ is young and inherits from _Mathematics_, _Engineering_,
_Nat. Sciences_, _Linguistic_, \dots\bigskip

Purely theoretical scientists whose practice is close to mathematics
/may/ not be concerned (can't publish a math article without
releasing the proofs).
- Have a look at [[http://www.math.ias.edu/vladimir/files/2014_IAS.pdf][talk by Vladimir Voevodsky in 2014 at Princeton]] \winkey\pause

#+BEGIN_QUOTE
Computer science is not more related to computers than Astronomy to
telescopes\vspace{-.6em}
\flushright              -- Dijkstra (mis-attributed)
#+END_QUOTE

Right, why should we care about computers? They are *deterministic*
machines after all, right?  \winkey \medskip

\textbf{Model $\neq$ Reality}. Although designed and built by human
beings, computer systems are *so complex* that mistakes easily slip
in...
** Experimenting with computers
#+BEGIN_EXPORT latex
\begin{tabular}{@{\hspace{-1em}}cc@{\hspace{-1em}}}
  \alert{Machines are \uline{real}!} & 
  \alert{Machines are \uline{complicated}} \vspace{.2cm}\\
  {\parbox{.5\linewidth}{\includegraphics[width=\linewidth]{images/shouting_in_the_data_center.jpg}}} &
 % \begin{overlayarea}{.5\linewidth}{1cm}
   {\parbox{.5\linewidth}{\vspace{-1cm}\includegraphics[width=\linewidth]{images/asplos09-producing-data_fig1.pdf}}}
 % \end{overlayarea}
\\
  \scalebox{.9}{\small \href{https://www.youtube.com/watch?v=tDacjrSCeq4}{Brendan Gregg: Shouting in the data center}}
  &\begin{minipage}{.5\linewidth}\small
#+END_EXPORT

  \vspace{-.7cm}Mytkowicz et al. /[[http://doi.acm.org/10.1145/1508284.1508275][Producing wrong data without doing
  anything obviously wrong]]!/ ACM SIGPLAN Not. 44(3), March 2009

#+BEGIN_EXPORT latex
  \end{minipage}
\end{tabular}\medskip
#+END_EXPORT

*Our reality evolves!!!* The hardware keeps evolving so most results on
old platforms quickly become obsolete (although, we keep building on
such results \winkey).

\bf We need to regularly revisit and allow others to build on our work!
 
** Computer performance ? Well, I design algorithms!
\small
- "Real" problems are all NP-hard, Log-APX, etc.

- Real workload = +NP-completeness proof widgets+, regularities and
  properties (difficult to formally state but that should be exploited)

Algorithms are evaluated on particular *workloads* that impact \\
both their running time and the quality of the solutions\bigskip\pause 

*Image Processing*: [[http://mescal.imag.fr/membres/arnaud.legrand/research/meinhardt_canum2016.pdf][True horror stories]], E. Meinhardt-Llopis, CANUM 2016
#+LaTeX: \begin{columns}\begin{column}{.6\linewidth}
- /The proposed multigrid algorithm converges to the solution of the
  problem in O(N)/ using biharmonic functions
- Surprisingly, our naive multi-scale Gauss-Seidel converges much
  faster\pause
#+LaTeX: \end{column}\begin{column}{.4\linewidth}
  #+LaTeX: \includegraphics[width=\linewidth]{images/meinhardt_canum2016_workload.pdf}
#+LaTeX: \end{column}\end{columns}
  
** I design Machine Learning Algorithms

#+LaTeX: \begin{flushright}\vspace{-1cm}\includegraphics[width=.13\linewidth]{images/Sandy-Pentland.jpg}\end{flushright}\vspace{-1cm}

*Machine Learning*:  [[http://www.economist.com/news/briefing/21588057-scientists-think-science-self-correcting-alarming-degree-it-not-trouble][Trouble at the lab]], The Economist 2013

  #+BEGIN_QUOTE
    According to some estimates, three-quarters of published scientific
    papers in the field of machine learning are bunk because of this
    "overfitting". \hfill -- Sandy Pentland (MIT)
  #+END_QUOTE

Every month in CACM, there is an article about the ethical
consequences of Machine Learning on:
- Car driving, Autonomous guns, Law enforcement (risk assessment, predictive
  policing), ...
  #+BEGIN_CENTER
  [[http://dx.doi.org/10.1145/3022181][It's Not the Algorithm, It's the Data]] (CACM, Feb. 2017)
  #+END_CENTER
- Advertising, Loan attribution, Selection at University, Organ
  transplant

#+BEGIN_CENTER
\bf Increasing society concern about *fairness* and *transparency*
#+END_CENTER

** All I care about is the algorithm output
Did I mention we have *parallel machines* nowadays? $\winkey$

#+BEGIN_EXPORT latex
\begin{overlayarea}{\linewidth}{7cm}
  \begin{center}
    \includegraphics<+>[width=.9\linewidth, page=13]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=14]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=15]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=16]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=17]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=18]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=19]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=20]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=21]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=22]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=23]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=24]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=25]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=26]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=27]{pdf_sources/langlois.pdf}%
    \includegraphics<+>[width=.9\linewidth, page=28]{pdf_sources/langlois.pdf}%
    \only<+>{
      \begin{flushright}
        \includegraphics[height=4cm]{images/langlois_malpasset.png}\vspace{-3cm}
      \end{flushright}\bigskip
      \begin{flushleft}
        These numerical issues can become \\ quite harmful in real use
        cases.
        \vspace{.5cm}
        
        \small TABLE 1.1: Reproducibility failure of the Malpasset test case
      \end{flushleft}\small
      \begin{tabular}{c|c|c|c}
        & The sequential run & a 64 procs run & a 128 procs run \\\hline
        depth H & 0.3500122E-01 & 0.2\alert{748817}E-01 & 0.\alert{1327634}E-01 \\\hline
        velocity U & 0.4029747E-02 & 0.4\alert{935279}E-02 & 0.4\alert{512116}E-02 \\\hline
        velocity V & 0.7570773E-02 & 0.\alert{3422730}E-02 & 0.75\alert{45233}E-02
      \end{tabular}}
  \end{center}
  \only<.>{
  {\bf \alert{Numerical reproducibility?}}: Approximations in the model, in
  in the algorithm, in its implementation, in its execution. \medskip

  The whole chain needs to be revisited.}
\end{overlayarea}
\begin{flushright}\scriptsize Courtesy of P. Langlois and R. Nheili\end{flushright}
#+END_EXPORT

* Toward Reproducible Computer Science Experiments ?
** Key Concerns for our Community (Room for Improvement)
- $\blacktriangleright$ Awareness of Experiments and Statistics :: /[[https://research.spec.org/fileadmin/user_upload/documents/rg_cloud/endorsed_publications/SPEC_RG_2019_Methodological_Principles_for_Reproducible_Performance_Evaluation_in_Cloud_Computing.pdf][How
     are cloud performance currently obtained and reported?]]/, March
     2019
    # 98 articles, 2012-2017
    #+ATTR_LaTeX: :width .9\linewidth
    file:images/SPEC_RG_2019_Fig4_2.pdf
    # - P3 discusses the experimental setup description. Even though
    #   more than 52% of the analyzed papers fully cover this
    #   principle, a substantial number of papers do not or only
    #   partially describe the experimental setup in which the
    #   performance evaluation is conducted. This significantly
    #   impacts the technical reproducibility of the results.
    # - P4 partly complements P3, as it considers the accessibility
    #   of the datasets used in the analysis and whether the authors
    #   have released the source code. In more than 70% of the
    #   cases, the code of the assessed technique is not released
    #   and the datasets used for the evaluation are not publicly
    #   available.
    # - P6 nalyzes if a statistical evaluation has been performed,
    #   to include some (statistical) confidence in the
    #   results. This principle is the most disregarded by the
    #   papers we study, with N > 90%.

\textbf{Key DoE principles}: _Replicate_ to *increase
reliability*. _Randomize_ to *reduce bias* $\leadsto$ _Evaluate_ *statistical
confidence*.

** Taming the Influence of Memory Layout
Remember Mytkowicz et al. /[[http://doi.acm.org/10.1145/1508284.1508275][Producing wrong data without doing anything
  obviously wrong]]!/ ACM SIGPLAN Not. 44(3), March 2009
#+LaTeX: \begin{columns}\begin{column}{.6\linewidth}
  #+BEGIN_QUOTE
  \small
  changing the size of *environment variables* can trigger performance
  degradation as high as *300%*; simply changing the *link order* of object
  files can cause performance to decrease by as much as *57%*.
  #+END_QUOTE
#+LaTeX: \end{column}\hspace{-1cm}\begin{column}{.4\linewidth}
  #+LaTeX: \includegraphics[width=\linewidth]{images/asplos09-producing-data_fig1.pdf}
#+LaTeX: \end{column}\end{columns}\medskip

C. Curtsinger and E. Berger /[[http://www.cs.umass.edu/~emery/pubs/stabilizer-asplos13.pdf][\textsc{Stabilizer}: Statistically Sound
Performance Evaluation]],/ ASPLOS 2013.

#+BEGIN_QUOTE
\small\textsc{Stabilizer} forces executions to sample the space of memory
configurations by *repeatedly rerandomizing* layouts of code, stack, and
heap objects at runtime. [..] Re-randomization ensures that layout
effects *follow a Gaussian distribution*, enabling the use of
statistical tests like ANOVA.
#+END_QUOTE
** MPI Performance Characterization: The many biases
#+LaTeX: \null\vspace{-1.5em}\small
- Powers of two for message sizes ? Linear ?
- Sensitivity to temporal perturbations \bgroup\scriptsize(in order =N_rep=)\egroup
- Breakpoint detection \bgroup\scriptsize(increasing message size, minimal range length, \dots)\egroup
- Outlier removal \bgroup\scriptsize(assumes normality, ignores uncertainty of previous measurements)\egroup

_Measurement proposal:_ \vspace{-.5em}
- Ping-Pong =data_size=
  #+LaTeX: $= 10^X, \text{ where } X \sim \mathrm{Unif}(\log_{10}(a), \log_{10}(b)).$
- Record the time taken in every =MPI_Send= and =MPI_Receive= operation\vspace{-.5em}

_Analysis proposal:_
#+LaTeX: \null\vspace{-.5em}\begin{multicols}{2}
- Manually provided breakpoints
- Regression in R 
#+LaTeX: \end{multicols}\null\vspace{-3.2em}
- Inspect regression output and hypothesis (linearity, noise, "outliers")

#+BEGIN_EXPORT latex
\centerline{\includegraphics[width=.8\linewidth]{images/randomization/reppar16/taurus_send_recv.png}}
Randomized measurements for Taurus (OpenMPI 2.0.1, TCP, 10Gb Ethernet).
#+END_EXPORT
** MPI Measurement: Randomization in action (Stampede@TACC)
#+BEGIN_EXPORT latex
\begin{overlayarea}{\linewidth}{7cm}
  \begin{center}
    \includegraphics<+>[height=6cm]{images/randomization/reppar16/stampede_send_recv_eth.png}
    \includegraphics<+>[height=6cm]{images/randomization/reppar16/stampede_recv_time.png}
    \includegraphics<+>[height=6cm]{images/randomization/reppar16/stampede_recv_time2.png}
    \includegraphics<+->[height=6cm]{images/randomization/reppar16/stampede_send_recv_local.png}

    \only<3>{c558-[203,304]} \only<+>{Even the simpler physical
      quantities can be very tricky to measure because our models and
      protocols are often naive}
  \end{center}
\end{overlayarea}
#+END_EXPORT
** Randomization of a Factorial Design
#+BEGIN_EXPORT latex
\null\hspace{-1cm}\begin{minipage}{1.0\linewidth}
  \uncover<1->{\includegraphics[width=.6\linewidth]{images/randomization/tom_hpl_random_perf.png}}%
  \uncover<3->{\includegraphics[width=.6\linewidth]{images/randomization/tom_hpl_random_temp3.png}}

  \uncover<2->{\includegraphics[width=.6\linewidth]{images/randomization/tom_hpl_random_temp1.png}}%
  \uncover<2->{\includegraphics[width=.6\linewidth]{images/randomization/tom_hpl_random_temp2.png}}
\end{minipage}
\begin{flushright}\scriptsize Courtesy of T. Cornebize\end{flushright}
#+END_EXPORT
** Randomize Everything! (Influence of Data)
#+BEGIN_EXPORT latex
\null\hspace{-1cm}\begin{minipage}{1.0\linewidth}
\includegraphics<+>[width=\linewidth]{images/randomization/tom_dgemm_random_init1.png}%
\includegraphics<+>[width=\linewidth]{images/randomization/tom_dgemm_random_init2.png}%
\includegraphics<+>[width=\linewidth]{images/randomization/tom_dgemm_random_init3.png}%
\includegraphics<+>[width=\linewidth]{images/randomization/tom_dgemm_random_init4.png}%
\includegraphics<+>[width=\linewidth]{images/randomization/tom_dgemm_random_init5.png}%
\end{minipage}
\begin{flushright}\scriptsize Courtesy of T. Cornebize\end{flushright}
#+END_EXPORT
** C.S. Experimental Methodology
#+ATTR_LATEX: :width .9\linewidth
[[file:images/R_workflow.pdf]]
\small
1. A *separation of concerns*
   - Transparent _Measurement Procedure_ and _Analysis Procedure_
2. *Randomized and Designed Experiments* allowing to both:
   - _Check_ the model and _Instanciate_ it
3. Careful *recording of all experimental parameters*
** Experimental Testbeds
- Good _experimental practice and platforms_ :: *FIT IoT-lab, G5K* are
  world leading experimental infrastructures
#+BEGIN_EXPORT latex
  \hspace{-1.5cm}\includegraphics[height=3.8cm]{images/fit_picture.png}%
  \includegraphics[height=3.8cm]{images/g5k_picture.png}%
  \includegraphics[height=3.8cm]{images/g5k_picture2.jpg}
#+END_EXPORT
\small
- These platforms are *fully configurable* (bare-metal OS deployment,
  isolation, network reservation, ...)
- *Share*: the maintenance cost (keeping in pace with technology),
  practices for prototype platforms, experimental conditions,
  experimental engines
** A few Experiment Management Tools
- Naive way: sh + ssh + ... \medskip
  #+BEGIN_EXPORT latex
  \item \alert<1>{Expo} (2007-, G5K)
  \item \alert<1>{XPflow} (2012-, G5K)
  \begin{overlayarea}{3cm}{0cm}
  \vspace{-2.5\baselineskip}
  $\left\}\begin{array}{l}
   \text{\phantom{X}}\\\text{\phantom{X}}\\\text{\phantom{X}}
   \end{array}\right.\hspace{-.7cm}
   \begin{array}{l}
   \text{although nothing} \\ \text{specific to G5K}
   \end{array}$
  \end{overlayarea}
  \item \alert<1>{Execo} (2013-, G5K) \medskip
  #+END_EXPORT
- Plush (2006-, PlanetLab)
- OMF (2009-, Wireless testbeds and Planetlab)
- Splay (2008, distributed algorithm comparison)
- ...

They differ in the underlying paradigms and the platforms for which
they have been designed

- *A taxonomy of experiment management tools for distributed
  systems*, T. Buchert, C. Ruiz , L. Nussbaum, O. Richard, FGCS, 2014
** Expo
Grenoble (B. Videau, C. Ruis, O. Richard)\hfill  http://expo.gforge.inria.fr/
- A Ruby-based *DSL* for experiment management (based on
  *taktuk*, i.e., sh + ssh)
- Expo interacts with *Planetlab* and *Grid5000* testbeds
- Resource and task abstractions, client-server organization,
  *interactive* or *batch* mode
- *Native logging and archiving capabilities* 
  + every action performed on tasks, error flows, dates, ...
  + lets you know *what* was run, *when*, *where* and *how*
#+LaTeX:\newsavebox{\temp}\begin{lrbox}{\temp}\begin{minipage}{1.3\linewidth}
#+BEGIN_SRC shell
reserv=ExpoEngine::new(@connection)
reserv.site=["bordeaux","lille","luxembourg","nancy","sophia"]
reserv.resources=["nodes=50","nodes=10","nodes=4","nodes=4","nodes=30"]
reserv.name = "Expo Scalability"
reserv.walltime=600

reserv.run!
ptask $all, "hostname"
reserv.stop!
#+END_SRC
#+LaTeX: \end{minipage}\end{lrbox} \scalebox{.8}{\usebox{\temp}}
** XPflow
Nancy (T. Buchert, L. Nussbaum)\hfill http://xpflow.gforge.inria.fr/
- Another Ruby-based *DSL* (Domain Specific Language)
  - Resources, process, and activities 
- Top-down vs. than bottom-up: *business process management*
  - Cope with *failures* through *snapshots* and retry *policy*
#+BEGIN_EXPORT latex
%\vspace{-.3em}
\begin{overlayarea}{\linewidth}{5cm}
\begin{center}
%\fbox{
   \includegraphics<+>[page=46,width=.9\linewidth,clip=true,bb=0 0 350 210 ]{./pdf_sources/xpflow_slides.pdf}%
   \includegraphics<+>[page=47,width=.9\linewidth,clip=true,bb=0 0 350 210 ]{./pdf_sources/xpflow_slides.pdf}%
   \includegraphics<+>[page=48,width=.9\linewidth,clip=true,bb=0 0 350 210 ]{./pdf_sources/xpflow_slides.pdf}%
   \includegraphics<+>[page=49,width=.9\linewidth,clip=true,bb=0 0 350 210 ]{./pdf_sources/xpflow_slides.pdf}%
   \includegraphics<+>[page=50,width=.9\linewidth,clip=true,bb=0 0 350 210 ]{./pdf_sources/xpflow_slides.pdf}%
   \includegraphics<+>[page=51,width=.9\linewidth,clip=true,bb=0 0 350 210 ]{./pdf_sources/xpflow_slides.pdf}%
%}
\end{center}
\vspace{-2.7cm}
\begin{flushright}
  {\scriptsize {\textbf{Courtesy of T. Buchert\qquad\null}}}
\end{flushright}
\end{overlayarea}
#+END_EXPORT 
* Conclusion
** Publish or Perish (ok, this is past and present)               :noexport:
- [[https://thegradient.pub/over-optimization-of-academic-publishing-metrics/][Goodhart’s Law: Are Academic Metrics Being Gamed?]], M. Fire 2019
  - AI: over 1,000 ranked journals ($\times10$ in 15 years)
  - Shorter papers with increasing self references
  - More and more papers without any citation
  - Sharp increase in the number of new authors publishing at a much
    faster rate given their career age
    # - Authors: We noticed a sharp increase in the number of new
    #   authors These new authors are publishing at a much faster rate
    #   given their career age than they have in previous
    #   decades. Additionally, the average number of coauthors per
    #   author considerably increased over time. Lastly, we observed
    #   that in recent years there has been a growing trend for authors
    #   to publish more in conferences.
    # - Papers: We observed that over time, papers became shorter while
    #   other features, such as titles, abstracts, and author lists,
    #   became longer. While the number of references and the number of
    #   self-citations considerably increased, the total number of
    #   papers without any citations grew rapidly as well.
    # - Traditional measures (e.g., number of papers, number of
    #   citations, h-index, and impact factor) have become targets 
    # - Citation number has become a target for some researchers
    # - Exponential growth in the number of new researchers who publish
    #   papers, likely due to career pressures
- [[http://users.cecs.anu.edu.au/~steveb/downloads/pdf/evaluate-toplas-2016.pdf][The Truth, The Whole Truth, and Nothing But the Truth: A Pragmatic
  Guide to Assessing Empirical Evaluations]], \textit{TOPLAS} 2016
  #+LaTeX: \begin{flushright}
    #+ATTR_LaTeX: :width .8\linewidth :center nil
    file:images/evaluate-toplas-2016_fig10.pdf
  #+LaTeX: \end{flushright}

#+BEGIN_EXPORT latex
\begin{overlayarea}{\linewidth}{0cm}
  \vspace{-5cm}\pause
%  \begin{flushright}
    \includegraphics[height=2.5cm]{images/ReScience-moto-bordered.pdf}
%  \end{flushright}

\end{overlayarea}
#+END_EXPORT

** Reproducible Research = Rigor and Transparency
To err is human. 

#+BEGIN_CENTER
\bf Good research requires time and resources
#+END_CENTER

1. \textbf{Train yourself and your students}: RR, statistics, experiments
   - Beware of checklists and norms
   - Understand what's at stake
2. \textbf{Change the norm:} make publication practices evolve
3. \textbf{Incentive}: consider RR/open science when hiring/promoting\pause
4. \textbf{Prepare the Future:} Toward *literate experimentation*?
   - Reuse, reuse, reuse!
   - Shared and controled testbeds (e.g., Grid'5000/SILECS)
   - How to share Experiments ?

\hfill\mylogo
** Some Advertising

#+LaTeX: \begin{columns}\begin{column}[t]{.45\linewidth}\centering
#+ATTR_LaTeX: :width \linewidth
file:images/ten-years-challenge.png

\footnotesize
http://rescience.github.io/ten-years/
#+LaTeX: \end{column}\begin{column}[t]{.54\linewidth}
#+ATTR_LaTeX: :width \linewidth
file:images/mooc_rr.png

\small
*3rd Edition*: \approx Feb. 2020\medskip

A *new MOOC*: "Advanced RR"\footnotesize
- Software environment control (Docker)
- Scientific workflow (snakemake)
- Managing data (HDF5, archiving)
October 2020 ?
#+LaTeX: \end{column}\end{columns}

* TILECS workshop : Recherche/Expérimentation/Analyse reproductible: comment se positionner? :noexport:
- [[http://users.cecs.anu.edu.au/~steveb/downloads/pdf/evaluate-toplas-2016.pdf][The Truth, The Whole Truth, and Nothing But the Truth: A Pragmatic
  Guide to Assessing Empirical Evaluations]] 2016 (Vitek, Diwan, ...)
- [[https://research.spec.org/fileadmin/user_upload/documents/rg_cloud/endorsed_publications/SPEC_RG_2019_Methodological_Principles_for_Reproducible_Performance_Evaluation_in_Cloud_Computing.pdf][Methodological Principles for Reproducible Performance Evaluation in
  Cloud Computing]] (2019, Amaral, Iosop, ..)

  http://users.cecs.anu.edu.au/~steveb/downloads/pdf/evaluate-toplas-2016.pdf

* Emacs Setup                                                      :noexport:
This document has local variables in its postembule, which should
allow Org-mode (9) to work seamlessly without any setup. If you're
uncomfortable using such variables, you can safely ignore them at
startup. Exporting may require that you copy them in your .emacs.

# Local Variables:
# eval: (add-to-list 'org-latex-packages-alist '("" "minted"))
# eval: (setq org-latex-listings 'minted)
# eval: (setq org-latex-minted-options '(("style" "Tango") ("bgcolor" "Moccasin") ("frame" "lines") ("linenos" "true") ("fontsize" "\\small")))
# eval: (setq org-latex-pdf-process '("lualatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
# End:
