#
# TransFig makefile
#

all: 2sample_comp_1.epic 2sample_comp_2.epic 2sample_comp_3.epic 2sample_comp_4.epic 2sample_comp.epic author_reader_rr_1.epic author_reader_rr_2.epic author_reader_rr_3.epic author_reader_rr_4.epic author_reader_rr_5.epic author_reader_rr.epic factor_impact.epic wp4_black_box.epic 

# translation into epic

2sample_comp_1.tex: 2sample_comp_1.fig Makefile
	fig2dev -L epic 2sample_comp_1.fig 2sample_comp_1.tex
clean::
	rm -f 2sample_comp_1.epic


# translation into epic

2sample_comp_2.tex: 2sample_comp_2.fig Makefile
	fig2dev -L epic 2sample_comp_2.fig 2sample_comp_2.tex
clean::
	rm -f 2sample_comp_2.epic


# translation into epic

2sample_comp_3.tex: 2sample_comp_3.fig Makefile
	fig2dev -L epic 2sample_comp_3.fig 2sample_comp_3.tex
clean::
	rm -f 2sample_comp_3.epic


# translation into epic

2sample_comp_4.tex: 2sample_comp_4.fig Makefile
	fig2dev -L epic 2sample_comp_4.fig 2sample_comp_4.tex
clean::
	rm -f 2sample_comp_4.epic


# translation into epic

2sample_comp.tex: 2sample_comp.fig Makefile
	fig2dev -L epic 2sample_comp.fig 2sample_comp.tex
clean::
	rm -f 2sample_comp.epic


# translation into epic

author_reader_rr_1.tex: author_reader_rr_1.fig Makefile
	fig2dev -L epic author_reader_rr_1.fig author_reader_rr_1.tex
clean::
	rm -f author_reader_rr_1.epic


# translation into epic

author_reader_rr_2.tex: author_reader_rr_2.fig Makefile
	fig2dev -L epic author_reader_rr_2.fig author_reader_rr_2.tex
clean::
	rm -f author_reader_rr_2.epic


# translation into epic

author_reader_rr_3.tex: author_reader_rr_3.fig Makefile
	fig2dev -L epic author_reader_rr_3.fig author_reader_rr_3.tex
clean::
	rm -f author_reader_rr_3.epic


# translation into epic

author_reader_rr_4.tex: author_reader_rr_4.fig Makefile
	fig2dev -L epic author_reader_rr_4.fig author_reader_rr_4.tex
clean::
	rm -f author_reader_rr_4.epic


# translation into epic

author_reader_rr_5.tex: author_reader_rr_5.fig Makefile
	fig2dev -L epic author_reader_rr_5.fig author_reader_rr_5.tex
clean::
	rm -f author_reader_rr_5.epic


# translation into epic

author_reader_rr.tex: author_reader_rr.fig Makefile
	fig2dev -L epic author_reader_rr.fig author_reader_rr.tex
clean::
	rm -f author_reader_rr.epic


# translation into epic

factor_impact.tex: factor_impact.fig Makefile
	fig2dev -L epic factor_impact.fig factor_impact.tex
clean::
	rm -f factor_impact.epic


# translation into epic

wp4_black_box.tex: wp4_black_box.fig Makefile
	fig2dev -L epic wp4_black_box.fig wp4_black_box.tex
clean::
	rm -f wp4_black_box.epic

